### ISSUE TITLE
Passwords not being sent / won't reset

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#499] opened 2018-07-16 14:08 UTC
Brenda has 5 new people in 5 days having issues.  She will send problem email to Vino

**Comment by smrr723** [comment] 2018-07-24 18:14
Just an update & note to myself as I work on this - the issue only appears for certain users.  My test user (Transcriber, Technical) was able to reset the password when I changed it to Yorkshire, System Admin.  

Still trying to identify the root cause.

**Comment by smrr723** [comment] 2018-07-25 21:59
Should be resolved now but can someone else also give the system a whirl and test it?

The error was caused by someone deleting the CENManager account for some reason... Culprit still to be identified.  I've set up a new account with that ID - need to know what email you want it to go to @FreecenBren - this is the new registration emails.

**Comment by FreecenBren** [comment] 2018-07-25 23:21
New registrations should go to the County COORD if the new volunteer has entered a choice of County.

 

Those that do not give their choice or select ‘ANY’ are sent to myself.

**Comment by PatReynolds** [comment] 2018-07-26 08:04
Just tested by signing up for Somerset (and let Geoff know why).

**Comment by smrr723** [comment] 2018-07-26 08:20
Great. That seems to work - I got the mail sent to Geoff (since CENManager is CC'd).  So I found a previous email from when I originally signed up that Brenda had forwarded to me, and Doug Kennard's email was listed for CENManager, so he would have been getting all the sign up mails before.

Who should I put in his place?  Brenda?

**Comment by FreecenBren** [comment] 2018-07-26 16:46
The COORDS should be getting the new Registrations for their County(s)

I know I get my Counties plus all the ones marked as “ANY COUNTY”

 

In the last week both Neil & Carol sent me an email saying the reset had not worked, along with some for my Counties, so I know they get copies.

 

Doug also got a copy when he set it up. I requested that Doug should be removed last month! It is on the Waffle Board somewhere?

 

Up to Pat if she wants anyone else to get them. 

 

We have to be careful there otherwise someone other than the COORD they register with might confuse the issue.

I think one email to the COORD should be all that is needed.

 

Brenda

**Comment by AlOneill** [comment] 2018-07-26 23:03
Er, maybe I am missing something here, but shouldn't the reset &c be through the syndicate coord?
Probably the same person as the county coord, but 2 different roles.

**Comment by PatReynolds** [comment] 2018-07-27 08:20
Yes, @AlOneill if it's to do with people, it's Syndicate, if it is to do with data, it's County.

**Comment by PatReynolds** [comment] 2018-07-27 08:52
Password reset also works fine.

**Closed** 2018-08-01 14:53 UTC
Labels: Sign-up, User Experience, bug, needs review
