### ISSUE TITLE
Identify all components of a piece

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1208] opened 2021-04-11 17:54 UTC
Pieces are given additional components to their numbers when they are split between counties. Coordinators need to be able to locate them

E0 U6 S9 C6: P21

**Comment by Captainkirkdawson** [comment] 2021-05-08 21:41
@geoffj-FUG @johnt-freecen @rhodamackenzie  Can I assume that the coordinator will specify a year? Will they also specify the original piece  that may have had parts moved? 
Without some degree of guidance it could be very time consuming task to look through all pieces to see if it has been split. We could start by finding all piece names that include and alphabetic character and look up the piece original piece number and see if they are different counties.
Alternatively perhaps we could look at combining the move results log to set up a collection  that can be reviewed. Assuming that @rhoda has kept them (I have not).

**Comment by rhodamackenzie** [comment] 2021-05-08 21:55
At the very beginning, i would change the letter at the end of a piece to the next one up the alphabet which had not been previously used. eg 1234A might become 1234E if the previous letters had been used in other pieces. Spreadsheets were sent back to the person who originally asked me to move parishes/pieces with the new piece number. This was getting very confusing so from the first week of February the letter A was added to the end, eg 1234A becomes 1234AA. If i have not sent coords the new piece number it will have an A at the end. 

I think the individual coords already have the required info and that it is a waster of time to try to pull it all together in one place. I certainly don't have time to do it.

**Comment by geoffj-FUG** [comment] 2021-05-09 06:19
The PARMS is a prime reference for Coordinators. Everything is based on piece numbers. Images come in batches for each piece number. Transcriptions will no doubt continue to be done by piece number even though that may mean that more than one spreadsheet is prepared. The breaking up of the PARMS has created a major problem in the Administration of Counties.
What is needed now is a table of pieces available to all Coordinators, indexed on the piece number. That means that when a Coordinator consults the table they will be able to see how many parts of the piece there are and what each piece covers. It does not need to be secured by County - all Coordinators should be able to see all of the centents.
I would suggest that the Coordinator selects a year and the table is displayed in piece number order for that year. Each piece number would have County, Piece name and the Places in the peice. 
Ideally it would also display whether there is a csv file on the system and if the piece has been Incorporated. 
If it is downloadable as a csv file each Coordinator can estract their part of the data from the csv file and create their admin records.
When FC1 is no longer available for uploads perhaps the pieces on the system can be identified and the table made complete.
I understand what Rhoda is saying but there will be new Coordinators in the future who will not have the information. At the very least we will have new Coordinators as Brenda eases her workload. Coordinators will also need to set up their record keeping when a new census year is started. Therefore we need to be able to reproduce this information in real time.
Geoff

**Comment by rhodamackenzie** [comment] 2021-05-09 13:25
A suggestion - if i could have a master list sent to me, i can go manually through any with a letter at the end and marry them up with what i have, then Kirk might be able to magic up a technique going forward so it updates in real time?

**Comment by rhodamackenzie** [comment] 2021-05-09 13:29
(I deleted my last comment of a few minutes ago)

I have just read Kirk's suggestion above - I have the logs of moves done since the 7th Feb and also have csv files of those, there are not a huge number so it would not take TOO long to put them together, then Kirk could perhaps work out a way of adding changes in real time as they happen, moving forward from now on

**Comment by Captainkirkdawson** [comment] 2021-05-09 20:45
@rhodamackenzie  before you do something let me have a look at Geoff's spec it throws a different light on how to respond.

**Comment by rhodamackenzie** [comment] 2021-05-09 20:51
thanks Kirk

**Comment by geoffj-FUG** [comment] 2021-05-14 11:44
@johnt-freecen <https://github.com/johnt-freecen>  @rhodamackenzie <https://github.com/rhodamackenzie>  

Yes the Coordinator will specify a year. That will set the filter.

If the file is then indexed on the piece number all associated piece numbers should appear together. (e.g. RG10_1111, RG10_1111A, RG_1111B etc) They will also be together in the ‘Home’ County of the original PARMS file before it was amended, with transferred to Counties interspersed between them. That is because they are in numerical order and the original TNA PARMS download is in numerical order. The other information requested just provides important information about the piece such as civil parishes etc.

 

If this is downloadable as a csv file the Coordinator can reconstruct their records from their part of this file. 

 

At the moment a Coordinator has no easy way of knowing where parts of a piece have gone. They need a picture of their whole County. As Pat brings new Coordinators on board the move log will make less sense to them, whereas a simple, but large, table will be understandable.

 

I know the csv file will be large but for Somerset for instance I need to be able to see the pieces that have been transferred of created in Gloucestershire, Devon or Dorset, not just the ones that are still in Somerset. Why? Because I have the images in one block and have to manage them. If I filter by County I can no longer see the transferred pieces. If everything is in the csv file I can extract the parts of the csv file I need.

 

I hope that this makes sense.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2021-07-12 03:44
@geoffj-FUG where do you want to see the action link? On the main action page or within a county. There are arguments for both options.

**Comment by geoffj-FUG** [comment] 2021-07-12 10:07
Kirk

 

My thoughts .

 

It is a Coordinator function. 

 

My logic says that it should be under Manage County. 

 

Perhaps under Manage FreeCEN2 Pieces. An additional index item at the end of
the menu 'List specific piece breakup'. The County filter should not operate
so that any piece entered for anywhere will be listed. That will help
Coordinators communicate with each other over problems and help them
identify where a piece that is not in their County on TNA came from.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2021-07-13 00:35
@geoffj-FUG Before I go any further have a look at **test3** for a possible implementation; not fully integrated .bbut is this what you had in mind![review all pieces.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/8783404a-26f6-41da-ac96-60d60e2cc899)
![3 options.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/5f31dab7-752b-4076-8e0d-6ea2f4e90211)
![selection.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/28d475bc-1201-4f87-89a9-e5068a2cecc1)

**Comment by geoffj-FUG** [comment] 2021-07-14 11:25
Kirk

 

Coordinators don't think in Civil parishes, they thing in piece numbers. So
the most useful option is option 2 and the least useful is option 3.

 

Looking at the length of the result there is a problem in that I either
scroll for a long time or cannot get near the piece I need with the
elevator. It would be easier if a Coordinator could type in the primary
piece number having selected a year and then the set with that primary
number would be displayed.

 

So selecting 1851:

Then 1927

The results for 1927, 1927A and presumably 1927B transferred to DEV would be
displayed together with a list of the Civil parishes in each piece. (The
list below is from the PARMS breakup exercise, the civil parishes would all
appear together in each piece).

 


11

Ashill

HO107_1927

Chard

Ashill

	OK


52

Broadway

HO107_1927

Chard

Broadway

	OK


121

Cricket Malherbie

HO107_1927

Chard

Cricket Malherbie

	OK


136

Donyatt

HO107_1927

Chard

Donyatt

	OK


138

Dowlish Wake

HO107_1927

Chard

Dowlish Wake

	OK


199

Ilminster

HO107_1927

Chard

Ilminster

	OK


200

Ilton

HO107_1927

Chard

Ilton

	OK


215

Kingstone

HO107_1927

Chard

Kingstone

	OK


333

Seavington St Mary

HO107_1927

Chard

Seavington St Mary

	OK


334

Seavington St Michael

HO107_1927

Chard

Seavington St Michael

	OK


338

Shepton Beauchamp

HO107_1927

Chard

Shepton Beauchamp

	OK


367

Stocklinch Magdalen

HO107_1927

Chard

Stocklinch Magdalen

	OK


368

Stocklinch Ottersay

HO107_1927

Chard

Ilminster

Amend to Stocklinch Ottersey

link updated


431

West Dowlish

HO107_1927

Chard

West Dowlish

	OK


448

White Lackington

HO107_1927

Chard

Ilminster

Amend to Whitelackington

link updated


58

Buckland St Mary

HO107_1927A

Chard

Buckland St Mary

	OK


107

Combe St Nicholas

HO107_1927A

Chard

Combe St Nicholas

	OK


218

Knowle St Giles

HO107_1927A

Chard

Knowle St Giles

	OK


414

Wambrook

HO107_1927A

Chard

Wambrook

	OK


449

Whitestaunton

HO107_1927A

Chard

Whitestaunton

	OK


469

Yarcombe

HO107_1927A

Chard

Combe St Nicholas

DEV

	

 

Geoff

**Comment by Captainkirkdawson** [comment] 2021-07-17 04:36
@geoffj-FUG I am sorry to say your suggestion is not implementable as the initial piece may already have an alphabetic character associated with it. I have spent 3 days trying to find a solution and reached a brick wall and in addition the "numeric" part is not numeric and may be 1-4 characters. Some other programmer may be able to develop such code but I cannot.

**Comment by Captainkirkdawson** [comment] 2021-07-20 01:31
@geoffj-FUG @rhodamackenzie I came at the problem a different way.
There is an Action called Locate
![locate.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/8aa111ad-1f12-4844-a017-540d2adfb5ea)
It takes you to a piece number entry
![piece.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/3f462771-bf35-4e8c-a2e3-913489c8a6b2)
Locate then looks for that piece number and any others that start with that number in the complete series.
![result.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/a57bd1d6-8705-4430-a2da-ef3a230c4d2b)
I do not know what piece moves have been done for SOM so it may not be especially enlightening. But if @rhodamackenzie has a move file for SOM we could run it on test3 so you can get a better sense of the action.

It is running on test3

**Comment by rhodamackenzie** [comment] 2021-07-20 19:09
i can't attach a csv file here but have sent moves files by email to Kirk and Geoff, so we can test on test3

**Comment by Captainkirkdawson** [comment] 2021-07-20 23:21
Thanks @rhodamackenzie  run on test3
Results for HO107_933 follow
![HO107_933](https://user-images.githubusercontent.com/2874694/126407265-85a087dc-6bbb-493f-abf5-b64ed36f685a.png)

**Comment by rhodamackenzie** [comment] 2021-07-20 23:22
Looks good!

**Comment by geoffj-FUG** [comment] 2021-07-21 10:54
Kirk
Just tested this.
Looks good. It solves the problem.
It always helps to have different perspectives. Your solution is perfect.
Geoff

**Comment by geoffj-FUG** [comment] 2021-07-30 10:27
Kirk
This can be deployed and I will let the Coordinators know. I will put out an explanation that will assist with all the queries.
Geoff

**Closed as completed** 2021-08-02 19:47 UTC
Labels: P21, Ready for Deployment
