### ISSUE TITLE
Civil Parish search

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#752] opened 2019-11-06 13:02 UTC

**Comment by Captainkirkdawson** [comment] 2020-03-31 14:54
This and the folio/page search requirement could be implemented in the same manner as the Christmas Present filtering.
Implementing a total restructuring of the database to make it a search parameter would be 20 times harder and longer

**Comment by Captainkirkdawson** [comment] 2020-04-19 00:57
This is duplicate of #331

**Closed** 2020-04-19 00:57 UTC
Labels: Data Management, Place, User Experience
