### ISSUE TITLE
Resolve the Red source issues in Geoff's Source report

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1369] opened 2022-02-05 16:40 UTC

**Comment by Captainkirkdawson** [comment] 2022-03-01 23:39
2/3rds of way through. Completed NFK

**Comment by Captainkirkdawson** [comment] 2022-03-06 19:14
Finished DTS; there are 45 left to do

**Comment by Captainkirkdawson** [comment] 2022-03-08 01:56
@geoffj-FUG  I have effectively completed the reds. However some of the large urban centre entries ae a mess as you have noted. I would like to spend some time getting then into a consistent structure. Before starting I wish to confirm that place naming should follow the larger smaller rule i.e. Leeds Beeston  should be the format NOT Beeston Leeds.
There is also the question of brackets. Do we include or not include? We are inconsistent. (The internal standard format used by the system drops them regardless)

**Comment by Captainkirkdawson** [comment] 2022-03-08 02:01
IMO if we are doing the bigger smaller rule we should bracket so as to indicate that is what has been done. ie. Leeds (West)

**Comment by geoffj-FUG** [comment] 2022-03-08 02:21
Kirk

 

Yes, Bigger to smaller.

 

Brackets are essential. We are looking at locking down duplicate entries by testing strings. So Wraxall (Nailsea) has to be differentiated from Wraxall (Shepton Mallet). The searching of POBs will need to take account of multiple lat/long entries if and when it ever happens.

 

Is Leeds West a place or not? I would validate it as the alternative Leeds. However, Leeds is a big area. West Leeds may be a legitimate place name. It is not in Genuki list of Leeds Parishes. So Leeds West is really Leeds West Riding of Yorkshire? It may well be a FC1 abbreviation given that it is Yorkshire. It should not even be in the Gazetteer. If it was entered as Leeds (West) then the system would not validate Leeds West and somebody would change it.

 

YKS is one of the big problems with Gazetteer entries. The number that I have in Anne’s spreadsheet of place names that do not have web addresses is incredible.

 

Geoff

**Comment by geoffj-FUG** [comment] 2022-03-08 02:43
Kirk

 

Further to my previous email.

 

If Leeds West is going to be entered to aid validation because it recurs in many pieces in many years, it should be an alternative name to show that it is Leeds. If should not be entered as a primary name.

 

The problem is changing people’s habits. Everything was entered in one list in FC1. No alternatives.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2022-03-08 04:58
@geoffj-FUG Leeds (West) would validate Leeds West because we validate on the standard name which is always shown on the Freecen2_place detail display

**Comment by Captainkirkdawson** [comment] 2022-03-08 22:35
@geoffj-FUG your argument about having all quadrants as alternates to the primary in cities makes logical sense. The counter argument is that doing so creates a single place with many hundreds of thousands of records and loss of specificity not to mention maxing out the results for common names. Hence I would urge retention of the sectorization.

**Comment by Captainkirkdawson** [comment] 2022-03-08 22:36
I have cleaned up leeds and think it looks better!!

**Comment by Captainkirkdawson** [comment] 2022-03-09 00:29
All red items dealt with

**Comment by geoffj-FUG** [comment] 2022-03-09 01:54
Thank you.

 

I will get the missing web address and invalid sources sorted out and then we can run another download and see how things look then.

 

The missing web addresses are being delegated to the Coordinators. Pat has already sent out a message to them that it is going to happen.

 

Geoff

**Comment by geoffj-FUG** [comment] 2022-03-09 07:25
Kirk

 

OK I understand

 

Geoff

**Comment by DeniseColbert** [comment] 2022-03-09 16:57
Done, closing

**Closed as completed by DeniseColbert** 2022-03-09 16:57 UTC
