### ISSUE TITLE
Add 'locate' facility to enable researchers to view places on map

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#1213] opened 2021-04-22 08:42 UTC
Geoff commented on story #869 in November 2020: 

We now have a Gazetteer of our own with Latitude and longitude. In transcription etc we can use a Locate button to open Google maps and see the place. In Validation we make sure that the POB is valid and in our database (unless we cant).
If this locate facility was added to the person in a household in the search results when Birth Places are displayed to the researcher, then the researcher could see the Place on Google Maps.

Pat adds: also potential to show on historic mapping - eg https://maps.nls.uk/geo/find/marker/#zoom=12&lat=54.2633&lon=-0.4536&f=1&z=1&marker=54.2631,-0.4380&from=1550&to=1909 (have to do a background map change to OS 1900 

E2 U3 S2 C6: P13

**Comment by PatReynolds** [comment] 2021-04-26 09:44
Parallel in FreeREG is the Location of an event in a record links to a page about that place which includes a Google Map button, lat and long, and details about the transcriptions made of that place (e.g. https://www.freereg.org.uk/freereg_contents/53cd4993eca9ebee4f00ae49/place?locale=en)

**Comment by Captainkirkdawson** [comment] 2021-12-05 22:59
Duplicate of https://app.zenhub.com/workspaces/freecen-5cb4e56573d7e234297de6c6/issues/freeukgen/freecenmigration/439

**Closed as completed by Captainkirkdawson** 2021-12-05 22:59 UTC
Labels: Actor: researcher, P13
