### ISSUE TITLE
London (and similar places) in the Freecen2 Place collection

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#960] opened 2020-09-06 23:17 UTC
How do we handle place names in Middlesex and London?
There are 2 aspects.
Firstly how to link the Districts/Pieces/Civil Parishes 
Secondly how to validate POB

Also applies to other metropolitan areas, e.g. Bristol and Manchester.

**Comment by Captainkirkdawson** [comment] 2020-09-06 23:23
London and Middlesex are significantly intertwined.  MDX encompases almost of London. Although some appears in KEN and SRY
The area that is now Inner London was defined by the Registrar General as a collection of parishes called "London" and appeared in the 1851 Census. for the first time.
Inner London is also known as the County of London
It existed until 1965.
The statutory Inner London boroughs are:

Camden (We have as KEN)
Greenwich (We have as KEN)
Hackney (We have as MDX)
Hammersmith and Fulham (We have as MDX) Both
Islington (We have as MDX)
Kensington and Chelsea (We have as MDX)
Lambeth (We have as SRY)
Lewisham (We have as KEN)
Southwark (We have as SRY)
Tower Hamlets (We have as KEN)
Wandsworth (We have as SRY)
Westminster (We have as MDX)

**Comment by Captainkirkdawson** [comment] 2020-09-07 02:12
Perhaps we should create the freecen2 places based on the district names in each of the freecen2  district names. This would provide linkages for districts, pieces and civil parishes and a basis for POB verification.
The question then would be with which year to start 1851 or 1911

**Comment by Captainkirkdawson** [comment] 2020-09-07 02:17
For POB verification we could expand the verification for LND to include, MDX, KEN and SRY in the same way we expand YKS to include the ridings and CHI to include the islands

**Comment by geoffj-FUG** [comment] 2020-09-10 06:17
The County of London was a county of England from 1889 to 1965, It was bordered by Essex to the north-east, Kent to the south-east, Surrey the south-west and Middlesex to the north. (Wikipedia) Prior to 1891 London was not a valid County. That is why the Place names file has MDX, SRY and KEN. 
We cannot use the POB verification that we used for YKS, (WRY, NRY, ERY) as the boundary of the County of London does not coincide with the boundaries of the other Counties whilst the Ridings were subsets of Yorkshire
So my view (which is a pedantic one) is that the acceptance of London for those parishes within the County should be accepted from 1891 and not before.
My query though is - How does it affect the proposed surrounding search area?

**Comment by PatReynolds** [comment] 2020-09-10 10:13
See also #448. #459, #309 and #805 for other aspects of the London Problem.
Also the story with the policy decision for resolution of some of these issues.  (will add when I find).

Tried again and still can't find. @richardofsussex  can you remember the story about how to facilitate searching in metropolitan areas?

**Comment by geoffj-FUG** [comment] 2020-09-14 01:24
This issue is being clouded by the Adminstrative County of London and the Traditional County of London definitions.
Let us look at Bristol as an example. Bristol is both a city and a county, since King Edward III granted it a county charter in 1373. The county was expanded in 1835 to include suburbs such as Clifton, and it was named a county borough in 1889 when that designation was introduced.
Despite all of this Bristol East of the River Avon is GLS and West of the River Avon is SOM The Censuses follow the traditional counties - there is no Chapman Code for Bristol. So when a POB is enumerated as Bristol Clifton we transcribe it as Chapman Code GLS. However the Places were Administered across County Borders as some Gloucestershire Places are on Somerset censuses. We have recorded these places against their Traditional Counties not where they were Administered.
LND (London) Chapman Code is defined as the City of London (a Traditional entity but not a County), nowhere else. However the Censuses appear to have used the Registration District (an Administrative entity) in lieu of the Traditional County in their structure. 
This does not affect the fact that North of the Thames is Middlesex and South of the Thames is Surrey , except the City of London. These are the Traditional Counties. 
My father was born in Lambeth. He always grew up in Surrey, though to the outsider he would refer to London. I grew up in a village 7 miles form Bristol but of you ask me where I came from I would tell you Bristol. If you had a knowledge of the area I would go into more detail. That is what seems to have happened in the censuses away from London.
FreeREG states that "Chapman codes are widely used abbreviations for county names. We use these three-letter codes when transcribing records as they save typing and need less space in the database than the full names". 
Wikipedia states that Chapman Codes are Administrative Counties. 
We do not have a general definition that we use within FreeUKGEN. The difference between Administrative Counties and Traditional Counties is causing our issues.
This document has been provided for comment.

**Comment by geoffj-FUG** [comment] 2020-09-16 21:34
[How to Handle London.pdf](https://github.com/FreeUKGen/FreeCENMigration/files/5235071/How.to.Handle.London.pdf)

I have now written a first draft solution to the London problem. It is fairly long so I have attached it as a pdf.

The issue is now extremely important. The solution will need to be agreed on before we migrate CSVProc.

Geoff

**Comment by Captainkirkdawson** [comment] 2020-09-19 21:11
@geoffj-FUG thank you for that excellent review. I have spent several days reading and rereading it hence the delay in responding
In my mind it does not **go far enough and propose specific guidance** on how we should handle Country Chapman Codes nor London as a conclusion.  Certainly there is insufficient guidance at this time for me to program the system appropriately and different coordinators will react differently to the document if that is their sole guidance.
The comments related to 1841 are I believe incorrect. The census was done in a similar manner as subsequent one. In that they were done by Registration District. All of the 1841 census sheets I have seen  indicate that. It was the decision of TNA to organize their index by hundred/wapentake/soke/liberty. See story **Decide how to handle the 1841 Hundreds as far as place name and location are concerned#975**
The difficulty I have in that the general public and census takers did not have the understanding that you and others have. People as you have said referred to their POB as being in a commonly known place eg London, Bristol, Yorkshire Scotland Ireland; they might have provided some additional specificity as I understand it.
**Remember the place collection is primarily made from the  Gazetteer of British Place Names and Genuki. It is not made from parms.**
We attempt to link the parms district, sub district and civil parish to places in that collection
Let's take some specific cases.
1) POB Norfolk Norwich My assumption would be NFK Norwich is entered. CSV Proc looks for it in NFK. As it is found it passes without a warning.
2) POB Yorkshire Hull .My assumption would be YKS Hull is entered. CSV Proc looks for hull in the 3 ridings. As it is found it passes without a warning.
3) POB London.  My assumption would be LDN - is entered and passed without warning
4) POB London Lambeth. My assumption would be LDN Lambeth is entered. CSV Proc looks for the place in LDN MDX, KEN ESS and SRY, and as found passes without a warning. 
It appears that what is proposed is that a warning should be generated on processing just against LDN and the validator researches and locates in SRY and enters SRY Lambeth. Is it worth the additional effort? Will it result is people adding Lambeth to LDN. 
Alternatively we run **no check** against LDN places which avoids the issue of additions to LDN
5) POB Scotland. My assumption would be SCT - is entered and passed without warning
6) POB Scotland Aberdeen My assumption would be SCT Aberdeen is entered and CSV Proc searches all scottish counties and is passed without warning.
It appears that what is proposed is that a warning should be generated on processing just against SCT and the validator researches and locates in ADB and enters ADB Aberdeen . Is it worth the additional effort? Will it result is people adding Aberdeen to SCT. 
Alternatively we run **no check** against SCT places which avoids the issue of additions to SCT

7) POB Aberdeenshire Aberdeen My assumption would be ABD Aberdeen is entered and CSV Proc searches ABD and is passed without warning.
8) POB England My assumption would be ENG - is entered and passed without warning
9) POB England Norwich My assumption would be ENG Norwich is entered and CSV Proc searches all English counties and passed without warning.
It appears that what is proposed is that a warning should be generated on processing just against ENG and the validator researches and locates in NFK and enters NFK Norwich. Is it worth the additional effort? Will it result is people adding Norwich to ENG. 
Alternatively we run **no check** against ENG places which avoids the issue of additions to ENG

**Comment by FreecenBren** [comment] 2020-09-19 23:45
Chapman Code for London Is *LND* and  not LDN.

It is a common mistake.

**Comment by Captainkirkdawson** [comment] 2020-09-20 00:39
You are correct @FreecenBren but what about the substance of the discussion?

**Comment by geoffj-FUG** [comment] 2020-09-20 06:36
Kirk

 

I know that I am beginning to sound pedantic, but what is being said is not what I was given to understand when I began as a Coordinator 15+ years ago. Nor is it what I see as written down.

 

So I am going back to basics. I have attached Fields.htm which is the instruction set that FreeCEN used to use.

 

If you look at the Chapman Codes London LND was specifically defined as London (City). London (City) is specifically Westminster and Whitehall (known as the one square mile). It does not encompass the County of London which was established in 1888.

 

Where a Place of Birth has been enumerated as London with no other information we have been pragmatic and entered LND – as the POB. But according to the definition of the London Chapman Code that is incorrect. Never-the-less it is an acceptable solution.

 

For the million plus records that I have validated in the past I have not accepted LND Lambeth or LND Harrow as valid when they occurred. I have entered a validator’s choice of Lambeth SRY or Harrow MDX. That is what the validator’s Choice was for. I have not put the LND options in my Placesup file to automatically validate them.

 

I was taught that the purpose of validation was to validate the data as far as possible, resolve any query flags as far as possible and enter the correct county and POB names wherever possible. In other words to create the best data set that we possibly could.

 

I have attached a document ‘Chapman Code Relationships’ that analyses my logic behind various Chapman Code suggestions for Yorkshire, Hampshire and London.

 

I cannot agree to the concept of automatically including all of Surrey, Middlesex and Kent (and certainly not Essex) into the Chapman Code of LND for automatic validation. The reasons are given in the document.

 

Validation has always been a human intervention because of its complexity. To broad brush its purpose means that we will eventually lose the respect for accuracy that we have from researchers.

 

Geoff

**Comment by johnt-freecen** [comment] 2020-09-20 10:45
I believe that in the examples of SCT - Aberdeen and LND - Paddington we should generate the warning messages for correction within the validation routine. The original Value in the verbatim county should be left as is and not rejected within the edit suite if a new value of County and place are entered in the appropriate fields.

We need a specific section in the Validation area of the new manual which covers this area and gives examples for people to follow. Could we amend the edit places routine to stop the addition of places to SCT, ENG, LND etc. If anything needs to be added it should be done on special dispensation by a central body.

**Comment by FreecenBren** [comment] 2020-09-20 10:51
As the COORD for London, I advocate AS IS.
If the enumerator has written London then LND  as the CHP, then we
transcribe it AS IS.
If there is also a POB then we also transcribe that AS IS.

Who are we to question something enumerated over 130 plus years ago that
the person being enumerated said where they were born!

The Transcriber is free to add an alternative in column Y if they feel it
is beneficial.
When you are transcribing London, which is the largest County by the number
of PIECES, checking every single one of them would be a nightmare.
Some transcribers who know or live in London will add an alternative CHP.
But then as we advocate AS IS, then that is their choice.

London,  and for that  matter Yorkshire, it was decided many moons ago that
we transcribe AS IS.
Why include Yorkshire.

The reason was that the transcribers were finding it very time consuming to
check every single entry for Yorkshire to establish which of the Ridings
the POB related to.
When you are doing other counties and you get the odd one or two for YKS or
LND for that matter, is is not such a problem.

It was therefore decided that we would keep to the AS IS rule, which was
what FreeCEN advocate anyway. This was decided by the powers that be.

We are here to transcribe what we see, AS IS.
It is up to the researcher to decide if they  want to go down the route to
check further with  regards to their ancestors actual POB.
That is where they can use FreeREG and FreeBMD.

I have,  just for the 3 Census years of 1861, 71 & 91  for London, over
1500+  separate PIECE numbers.
Also London contains a lot of shared dwellings, and lots of foreign
residents as well to deal with.

I will not be a ‘Happy bunny’ If you decide that you wish they all be
 checked for an alternative county (CHP).
The transcribers have enough to deal with as it is.

I will be very pleased to pass all of London over to someone else who would
like to take it on, who probably has more time on their hands than I do.

This is just my take on what we advocate AS IS and have done so for the 21
years I have been with FreeCEN.

Brenda

**Comment by geoffj-FUG** [comment] 2020-09-20 10:52
Thanks John

 

That is what I have suggested. My suggestion is that Places can only be added to the level 3 Chapman Codes shown in my table.

 

The issue now is what constitutes London? There are varying opinions.

 

I have added a new item to Story #960 outlining my logic on how to handle Yorkshire, Hampshire and London.

 

Geoff

**Comment by geoffj-FUG** [comment] 2020-09-20 11:10
Brenda

 

There is no dispute as to whether we transcribe ‘as is’ or not. 

 

The issue is how do we handle the Warnings that are generated when the Place is in the Place Names database as say SRY but it has been enumerated as LND. See my Venn diagrams posted this evening. They explain the problem of just accepting LND when the place is in say KEN.

 

There is no FreeCEN interpretation of London in the Chapman Codes. The Chapman Codes are specific (London City). Practice has been broader. If we can agree on a practical interpretation then this issue will be resolved. We can set a rule and a Place will either fall into or out of London.

 

There is no issue over Yorkshire. There is no change, it has already been coded in. YKS and the three Ridings are contiguous. It was used as a comparison example. See my original document.

 

We want to achieve a system that is not onerous, but still accurate. We have to do it now or it wont get done. The rules have to be transparent or this will all be revisited in a ten years when the current crop of ‘experts’ have moved on. I am sure that this was all covered 20 years ago but no history remains. If we can document it then it shouldn’t raise its head again.

 

You will find that validation is getting easier in the new system. It will take time to populate some of the Places but it will happen over time and validation should become very easy. We just have to decide the rules to be able to populate the Places in the London area.

 

Geoff

**Comment by geoffj-FUG** [comment] 2020-09-20 11:42
Kirk

 

Comments below that I have not covered elsewhere:

 

1.	Correct
2.	Correct
3.	Correct
4.	This is covered in my Venn diagrams. John has given us feedback and suggested that additions to London can only be made centrally. That would control the spurious entries. Another suggestion is that the Places listed in the County of London table that was in the document with the Venn diagrams be added centrally to the database under LND and LND be locked out from universal additions.
5.	Correct
6.	Incorrect. SCT Aberdeen is entered. The validator would enter ABD Aberdeen in the Alternative Place of Birth fields.
7.	Correct
8.	Correct
9.	Incorrect. ENG Norwich is entered. The validator would enter NFK Norwich in the Alternative Place of Birth. England is a level 1 Chapman Code in my table. Nothing should be able to be attached to it.

 

The concept of my table is that Places cannot be attached to level 1 and level 2 Chapman Codes, only level 3.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2020-09-20 16:01
@geoffj-FUG  Your proposed attachments were not added I am afraid.

**Comment by geoffj-FUG** [comment] 2020-09-20 21:31
[Chapman Code Relationships.docx](https://github.com/FreeUKGen/FreeCENMigration/files/5252693/Chapman.Code.Relationships.docx)

One attachment - the Venn Diagrams
Kirk - The other is html. I will forward it to you.

Geoff

**Comment by geoffj-FUG** [comment] 2020-09-20 21:54
Kirk et al

 

I have come up with 2 possible solutions to our problem. They are both technical solutions.

 

The first is that we have the Latitude and Longitude of the centre of London. We have the Latitude and Longitude of our Places. So if a Place is say within, say, 25 Km of the centre of London and it is in our Place Names Database we accept LND as the Chapman Code and do not create a Warning. This can be coded. The M25 is approximately 25Km from the centre of London as the crow flies. This solution would accept anywhere within the M25 as LND.

 

The second proposition is that we ask the Validators for London for a copy of their Placesup file. These will have a very detailed list built up over many years of Places that have previously been accepted as being in London. If we then

Select Unique Place WHERE Chapman Code = ‘LND’ 

We will have a good list of valid London Places

Next step would be to do an extract from the Place Names Database.

Select all WHERE Place name in ‘our new set of records’ AND Chapman Code in ‘SRY, KEN, MDX’

Now we can change these Chapman Codes to LND and Append them to the Place Name Database.

 

Either solution should give us a practical way of achieving a workable Validation system.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2020-09-20 22:42
It seems that we are getting close to an understanding on how to proceed.
Let me repeat what I have said many times; I have never been involved with Freecen in any capacity (not even as a user) until I became involved with the implementation of FreeCEN2 as a modern input/output platform.
In this capacity I may make stupid suggestions, forgive me I know no better. However in this capacity I must understand exactly **with no fudging** what is being requested. Code is black and white.
With respect to @FreecenBren concern. From all I have done there has been NO deviation from TWYS with respect to the input fields.
The discussion here is what to do with POB entries from a validation perspective. Explicitly what and how to flag entries that may need the attention of the validator.
Based on the discussion prior to the comments of @geoffj-FUG today the specification as I now understand it follows for all except London is:
 1. POB NFK Place is entered. CSV Proc looks for Place in NFK. If Place is found it passes with no observation. If Place is not found a warning is raised. This applies to all tier 3 chapman codes 
2. POB YKS Place is entered. CSV Proc looks for Place in WRY, ERY and NRY. If Place is found it passes with no observation. If Place is not found a warning is raised. The same applies to CHI where JSY GSY ALD SRK are searched. For IOW and HAM both IOW and HAM are searched.
3. POB SCT - is entered.CSV Proc will  pass with no observation. The same for LDN, ENG, IRL and WLS.
4. POB SCT Place is entered and CSV Proc will raise a warning. The same for ENG, IRL and WLS (Note LND is deliberately left out here and subject to further discussion)
5. The Place Names collections for LND, YKS, CHI, ENG, IRL and WLS are closed. No places can be added.
Do we agree on this specification?

**Comment by geoffj-FUG** [comment] 2020-09-20 23:03
Kirk

 

I agree wholeheartedly. 

 

I recognise that we have to come up with an objective rule so that it can be coded. That rule is then fitted into the FreeCEN process.

 

Validation has been up to the Validator for so long that inconsistencies have arisen in the interpretation. I have taken a narrow view in trying to come up with a solution and gradually expanding it until we come up with something practical. I recognise the balance between the two positions. 

 

I have replied to Brenda regarding ‘as is’ and reassured her that we are not digressing from that position. 

 

Comments re 1-4 below

1.	Correct
2.	Correct – I had neither thought about nor addressed Channel Islands in my Venn diagrams. I need to consider whether CHI equates to a level 1 or level 2 Chapman Code. At present I have it as a level 1, in which case the sub-codes would not apply.
3.	Your first 3 -  Correct
Your second 3 – Correct
4.	Correct

 

Looking at my chart level 1 and 2 cannot have place names attached. Level 2 cannot have place names attached but can be validated if the counties is against it in level 3.

 

I have added Hampshire to  level 2 with Hampshire (again) and Isle of Wight as entry points in  3. i.e. Either HAM or IOW are validated as HAM by the system.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2020-09-20 23:46
Now for LND. 
The original spec for LND is as the City of London. It was an administrative area as @geoffj-FUG has observed and was not a traditional county. 
The Places within the Places collection for LND are the wards. It has:-
 Aldersgate ,Aldgate ,Bassishaw ,Billingsgate ,Bishopsgate ,Bread Street ,Bridge ,Broad Street ,Candlewick ,Castle Baynard ,Cheap ,Coleman Street ,Cordwainer ,Cornhill ,Cripplegate ,Dowgate ,Lime Street ,Portsoken ,Queenhithe ,Vintry 
The following appear to be missing: Farringdon,Langbourn,Tower,Walbrook.
The following had 'within' and 'without' :Bridge ,Farringdon.
The census parms all have a London City district. From 1851-1881 it was located in Middlesex. In 1891 and there after it was located in London. 
Does the following make sense?
CSV Proc validate LND Places against the places in the City of London. Passing them if found. If not extend the search to include Middlesex, Surrey and Kent. If found it raises a warning but notes that it was found in which ever of the counties. If not found then the standard warning  that it was not found is raised. The validator this way has the ability to use the information or not as they see fit.
We might wish to add the parishes of LND to the Places collection. Most of them were based on a church. This would be a one time effort. 

![City_of_London_Ward_Map,_1870.svg](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/881dd7e7-df6e-4f6c-8dcc-b708d04868b1)
by By Doc77can - Own work, CC BY-SA 4.0, https://commons.wikimedia.org/w/index.php?curid=35553886

**Comment by geoffj-FUG** [comment] 2020-09-21 00:28
Kirk

 

It sounds like a good start.

 

If we can give Paul Tollemache access to the live database I can get him to populate it with LND Places. His strength is the accuracy of his transcriptions so he would be a good one to do this. He also researches places well.

 

I can get him to look for Place Names within Wards. He can add these as well. That should give us a very good database to go live with.

 

He can also add the Parishes for us.

 

He is very thorough.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2020-09-21 00:53
@geoffj-FUG We can provide Paul with access at the appropriate time.
Please bear in mind that the LND places are a very small number. Places like Westminster are not part of LND.
As we have discussed the test3 databases cannot be moved as they are likely damaged as part of our testing.
These changes must be done to the production database.
That cannot be done until the code base is deployed to production. 
We are a few weeks away from that I am afraid. While I think we have the major parts working or close to working there are a fair number of little bits and pieces to be added and deployment requires a decision by management.

**Comment by geoffj-FUG** [comment] 2020-09-21 01:45
Kirk

 

That is fine. We can make sure that LND is not validated until we are ready. 

 

That is unlikely anyway as it is at the end of the pipeline.

 

I have put it on my to do list.

 

Geoff

**Comment by geoffj-FUG** [comment] 2020-09-21 10:10
Kirk

 

I would like to leave CHI as a level 1 Chapman Code. It falls into the same group as England, Wales, Scotland etc.

 

CHI – is accepted in a similar way to ENG -. Any other entries need the Island in the similar way to the Counties.

 

I have attached a new table and comments. This is what will go into an appendix in the Handbook as a Technical note. Are we on the same wavelength?

 

Geoff

**Comment by geoffj-FUG** [comment] 2020-09-21 11:30
Kirk

 

I have been looking at your list of Wards in 1870 and this list of Parishes in 1891. This list is broader but contains most of the Parishes that from my experience are usually enumerated as London. The Wards list only contained Middlesex. The area South of the Thames is equally important.

 

https://en.wikipedia.org/wiki/List_of_civil_parishes_in_the_County_of_London_in_1891

 

It would make validation less onerous if we used this list instead and it would address most of Brenda’s concerns.

 

It would also meet FreeCEN requirements right up to and including the transcription of the 1961 census.

 

From a lay point of view this is a reasonable definition of London as well as having a geographic rationality.

 

I have asked Brenda for a copy of a London Validator’s Placesup.gen file so that I can verify what the expectations are.

 

Whichever option is decided on it will be locked in.

 

Geoff

**Comment by geoffj-FUG** [comment] 2020-09-21 21:25
Kirk

 

Having slept on it I am strongly in favour of London being defined as the 112 Parishes and 4 Part Parishes in the County of London in 1891. 

See https://en.wikipedia.org/wiki/List_of_civil_parishes_in_the_County_of_London_in_1891 

 

This effectively means that we have redefined the Chapman Code from London (City) to London (City and County). This is neat and tidy. It covers  Parishes in MDX, SRY and KEN and the areas listed would have colloquially been in London at the time.

 

Brenda – Does this address your concerns?

 

I am feeling very comfortable with this definition. 

 

Geoff

**Comment by Captainkirkdawson** [comment] 2020-09-21 21:37
@geoffj-FUG Sorry but this has totally confused me, never difficult these days.
I had thought that we had reached the conclusion that LND would retain its status as the City of London.  
Only POB that were in the wards of the City would pass validation without comment All others would be warned. Those that were in found in Middlesex, Surrey or Kent would have this information included in the warning.  Thus enabling the validator to easily Alternate **County** POB. This would apply to the census of 1841-1881. 
We had not explicitly discussed 1891 onwards. The list you linked to is a list of those Civil Parishes removed from Middlesex, Surrey or Kent and were now in the county of London. If we were to add these to LND and use that County of LND list we would now pass those without warning. This means the validator would no longer be warned that these places be in their traditional counties. eg POB LND Lambeth would now be accepted; POB LND Whitechapel would be accepted. POB LND Greenwich would be accepted. POB LND Harrow would not be accepted. KEN would be suggested. POB LND Ealing would not be accepted. MDX would be suggested.
This is possible but the addition of these would be locked once made.

**Comment by Captainkirkdawson** [comment] 2020-09-21 22:41
@geoffj-FUG looks like our messages crossed.
If you and @FreecenBren  are happy with that it can be implemented.
The only change I would propose is that we include the City of London ward civil parishes there are 80 of them.

**Comment by FreecenBren** [comment] 2020-09-22 10:24
Hi,
 
I wrote this reply yesterday but it did not go. Crossed over with others now so still sent it.
Ignore it if you wish! My pennies worth for what it is.
 
Brenda



Hi.
 
If Geoff is confused then I to am totally confused.


We could talk about this all day,  and still not reach a compromise.

But if we stick to the AS IS  for the POB option, then if it ‘pops up’ in FC2 to suggest an alternative CHP,  then that should go in what we call the ‘Column Y’ in FC1. 
As we manually do today.
Sorry not got around to any testing so I am sure someone will correct me.

The following are just some of the quotes from Google about what is in London and what is not.
So how are we mere mortals, going to decide, when the governments of the day move things around. The 1965  re-arranging was one of the latest I picked up.
We must therefore when we make a decision that things  probably alter again after the 1911 Census. 
Will be interesting to see what 1921 has in store.


These are the ones I chose, but there are plenty more. (1891 Ealing is part of Brentford in MDX Census)



1. London Borough of Ealing


Description

The London Borough of Ealing is a London borough in West London. It comprises seven major towns: Acton, Ealing, Greenford, Hanwell, Northolt, Perivale and Southall. Ealing is the third largest London borough in population and eleventh largest in area, covering part of West London and a small part of Northwest London.
2. Wembley (/ˈwɛmbli/) is the principal town of the borough of Brent in north west London, England, about 8 miles (13 km) west-northwest of Charing Cross. Wembley was formed a separate civil parish from 1894 and was incorporated as a municipal borough of Middlesex in 1937.
https://en.wikipedia.org/wiki/Ealing
 

3. The areas it covers

Greater London, most simply, is bounded to five counties; Hertfordshire, Berkshire, Buckinghamshire, Kent and Surrey.
The Greater London region consists of 33 districts which include the City of London, the 12 London boroughs and then the 20 Outer London Boroughs.
Outer London Boroughs are as follows:
*	Barking and Dagenham
*	Barnet
*	Bexley
*	Brent
*	Bromley
*	Croydon
*	Ealing
*	Enfield
*	Haringey
*	Harrow
*	Havering
*	Hillingdon
*	Hounslow
*	Kingston upon Thames
*	Merton
*	Newham
*	Romford
*	Redbridge
*	Richmond upon Thames
*	Sutton
*	Waltham Forest
 
The simple way round it is to stick to AS IS.  But that is just me choosing the easiest route.
If I was one of those in the 19th Century residents, I would want recording the CHP and the POB where I was born, and the enumerator recorded on the census, and not want it changed.
Just an alternative offered if that comes up.


Not my decision. I have therefore decided to leave it to you ‘experts’ to decide. I will go along with whatever you all decide on.
 
 
ps. 
Added information regards LONDON.
I have attached details from the 1891 census that shows what areas the 38 Census Discs for London,  that we use to do the transcriptions, says.
Just for information for you as to what the transcriber has available if needed.
The CD’s also include all the Street Names of the City of London. (Quite a lot and also ALL the street names for the whole of 1891 census) ) if anyone is interested.
 
As a little note. It is nice to see that Ealing (including Wembley) is in London, (Even if it is also part of MDX)  otherwise when I drove down there I would have got lost!


Anyway, cowards way out, but I really  have enough to do  with looking after over 200 of my helpers and 34 counties, and trying to cope with Vertigo as well.
Sorry about that.  
 
I will therefore go along with whatever you all decide.


The only words I can add to that is please try to make it as simple as you can.
With many of our volunteers all in the ‘Over 60’s and many others over 70 - 80’s as well groups, it will be hard for them to make the transition as it is.
I do include myself in that as well!
 
Brenda

**Comment by Captainkirkdawson** [comment] 2020-09-22 14:04
@FreecenBren  it was me (kirk) who was confused not Geoff.
As noted earlier nothing about the  POB county and Place fields is changed. They remain TWYS.
CSV Proc is looking at what is in the POB county and Place fields. Seeing if they are valid and if not either just saying so or making a suggestion so that the **validator** can take action based on that information as they do today such as manually entering a suggestion in the **alternate POB fields**.

**Comment by Captainkirkdawson** [comment] 2020-09-22 16:11
The apparent agreement is documented in https://drive.google.com/drive/u/1/folders/150Uh4r_lvGT9_nVaxf3R4wvvub3EoyDI
Adding an additional story to populate LND after deployment of the software
Populate the LND Place Names#984

**Comment by geoffj-FUG** [comment] 2020-09-27 11:24
Paul T has started entering the LND Places into a spreadsheet. These will converted to a .csv file be loaded into the Place Names Database at cutover. The area concerned is the City of London  Wards, the City of London Parishes and the Metropolitan Boroughs. These entries generate Place Names and Alternative Place Names. These are all being recorded.
This will give us a good starting point for London Place Names. I am sure that we will need to add some more - as will happen for all Counties. I have had a look at a couple of 1871 spreadsheets and I think we have validatoon fo London covered fairtly well.
I will let you know how Paul goes. 
Geoff

**Comment by richpomfret** [comment] 2020-09-28 16:17
Closing following review in FC scrum.

**Closed as completed by richpomfret** 2020-09-28 16:17 UTC
