### ISSUE TITLE
Mouse-over alt text and/or hyperlinking of more obscure contractions

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#253] opened 2017-05-15 13:11 UTC
e.g. Chapman codes

**Comment by PatReynolds** [comment] 2018-02-06 10:16
@AlOneill notes Need to consider those volunteers who can't use a pointing device

**Comment by Captainkirkdawson** [comment] 2020-08-01 18:07
Duplicate of #866 which has been actioned

**Closed by Captainkirkdawson** 2020-08-01 18:07 UTC
