### ISSUE TITLE
Citations error - always shows 1891 census returns

### ISSUE THREAD

**Issue by richpomfret** [FreeUKGen/FreeCENMigration#734] opened 2019-09-23 15:05 UTC
'Your Wikitree citations start with the words "General Register Office: 1891 Census Returns" no matter what year the census is. For example, here is a Wikitree citation for the 1861 census - "General Register Office: 1891 Census Returns" "General Register Office: 1891 Census Returns" database, FreeCEN (https://www.freecen.org.uk/search_records/590427e8e9379091b1bd1181 : viewed 22 Sep 2019), David HUDSTON in household of Francis HUDSTON, Nether St, Basford, Nottinghamshire, England; from 1861 "England, Scotland and Wales census," database and images; citing PRO RG 9/2440, Folio 55, Page 10, Schedule 54, The National Archives, Kew, Surrey." Please could this be corrected so it shows the correct census at the beginning of the citation.'

Applies to all citations, not just Wikitree.  A new error - was fine before.

Pe3, U3, S6, C?7: P19

**Comment by PatReynolds** [comment] 2019-09-23 15:22
This is a new error - was correct before.

**Comment by richpomfret** [comment] 2019-09-25 15:12
@ShemJM hope you are well - any chance you might be able to take a look at this fix?

**Comment by ShemJM** [comment] 2019-09-25 16:09
Hi, yes I Will have a look this evening.

**Comment by richpomfret** [comment] 2019-10-23 14:58
@ShemJM any update on this story?

**Comment by ShemJM** [comment] 2019-10-23 20:27
@richpomfret I think I know how to fix it but I am having trouble with my local setup of the app. I need to spend some time get it working again. Maybe even do a fresh install.

**Comment by Captainkirkdawson** [comment] 2019-10-26 16:41
That wording was added in response to https://github.com/FreeUKGen/FreeCENMigration/issues/713
Guess I misunderstood the original request.

**Comment by ShemJM** [comment] 2019-10-31 21:00
Sorry, what is happening with this one? Kirk and I established it is not a bug.

**Comment by PatReynolds** [comment] 2019-11-01 09:33
Hi both.  Some comments from slack on 7 October, tiedied for clarity:
"England, Scotland and Wales Census" is correct (because this line of code makes it appear in each record in the database, not just those from the 1881 census). 
For Wikitree it is "General Register Office: 1841 Census Returns" database, FreeCEN (https://www.freecen.org.uk/search_records/5c38d194f4040b8d3250d862 : viewed 7 Oct 2019), John ALCOCK in household of John ALCOCK, Newark on Trent, Nottinghamshire, England; from 1841 "England, Scotland and Wales census," database and images; citing PRO HO 107/14, Folio 21, Page , Schedule Parliament St, The National Archives, Kew, Surrey. 
The year after "General Register Office:" should be the year of the census;
For Scottish records, the title should be changed for Scottish censuses to "Scottish General Register Office: [year] Census returns". (where [year] is the year of the census.

**Comment by ShemJM** [comment] 2019-11-14 20:57
I have my localhost up and running again, and have started work on this. Sorry for the delay. I just noticed that the MLA citations have "England and Wales Census, 1861" hardcoded in, is that correct?

**Comment by ShemJM** [comment] 2019-11-29 07:24
I think my citation changes were merged in the last build. Are the citations ok now?

**Comment by richpomfret** [comment] 2019-12-04 17:31
@PatReynolds can you take a look and test this for Shem?

**Comment by richpomfret** [comment] 2019-12-04 17:31
It's now in Production.

**Comment by PatReynolds** [comment] 2020-01-03 10:12
All good - except everything now shows Scottish Record Office.

**Comment by ShemJM** [comment] 2020-01-06 19:39
That's not good....

**Comment by Captainkirkdawson** [comment] 2020-01-06 23:49
@ShemJM fixed. Deployed to test3

**Comment by PatReynolds** [comment] 2020-01-07 10:03
Tested and working fine (year issue and Scottish / not Scottish issue both resolved on test3).

**Comment by Captainkirkdawson** [comment] 2020-01-30 23:32
deployed

**Closed by Captainkirkdawson** 2020-01-30 23:32 UTC
Labels: P19, Ready for Deployment, bug
