### ISSUE TITLE
Amending PARMS

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#807] opened 2020-02-12 15:39 UTC
On Tue, 11 Feb 2020, 10:46 , brenda. wrote:
![image002.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/c0ba10e6-98a1-47a9-a518-23eb16e3dcbc)
I am sorting out issues with the PARMS but came across this one.

 

When you do an update from FC1 for an amended PARMS it replaces the current one and you can see the amended one in FreeCEN One on the STATS page link.

example https://freecen1.freecen.org.uk/coverage-DOR.html#1871

 

I assumed it did the same in as well in FC2.

Well it did replace the new details OK on the TRANSCRIPTION link at. https://www.freecen.org.uk/freecen_coverage/DOR#1871

So at this stage no problem. FC1 STATS matches the FC2 TRANSCIPTION link. Both links above

What I also expected it to do in FC2 was to delete the Census Places errors  from the search page as example below.

I assumed wrongly.

It just added the new one to the existing one, in this example for Dorset 1871.

So we are left with the Netherbury 3A and Netherbury 3B  and many others like them, that are no use to us.

The 3A and 3F , to name just two, should never have been added to the PARMS in the first place.
There are quite a few like this.

 

In summary and example of a search in FC2.

 

Example  above for Dorset 1871.

In the amended Parms these Netherbury 3A and Netherbury 3B were replaced with just Netherbury.
It therefore was amended it to read on the search page as Netherbury (Dorset 1861,1871)  (It added the 1871 one as it should do)
It did not however remove the Netherbury 3A and Netherbury 3B, from the original Parms which I was hoping it would.
 

If you now search for say Smith, Dorset 1871 select Netherbury (Dorset 1861’1871) in the Census Place  and you will get 75 results.
 

If you do exactly the same search and select Netherbury 3A instead you get no results just as before.
So these Netherbury 3A etc., should be removed from the search page as I expected they would!

I assumed, quite wrongly, that when the newly amended PARMS was replaced in the Transcription place in FC2,
it would delete the original census Places with those numbers of 3A, 4G, etc.   from the Census Place on the FC2 search page
https://www.freecen.org.uk/freecen_coverage/DOR#1871    but it did not it left them there.
 

Do we want to leave them there or not?
 

Not my choice, just letting you know what I found.

**Comment by PatReynolds** [comment] 2020-02-21 16:52
On 
14 Feb 2020, 15:31 Brenda email > Pat
This is what I have taken from some past records.

The time lapse ones are due to FC2 not been done till later for various reasons.

Whereas FC1 is done every 4 weeks.

 

But it will give you an idea anyway.

Perhaps the 39,000,000 might be due to a misprint!

As you can see there is a steady climb for both FC1 and FC2.

All the months are not there as it depends on my time etc. and if I kept them all.

 

Date

FC1

FC2

Difference

Reason

Jan 13th 2017

31,825,471

31,674,348

151,123

 

01 June 2018

35,159,594

35,171,232

11,638

 

Jan 1st 2019

36,087,020

36,076,413

10,607

 

Jan 8th 2019

36,446,539

36,076,413

370,126

Time lapse

Feb 5th 2019

36,573,730

36,076,413

497,317

Time lapse

March 5th 2019

36,778,298

36,551,311

226,987

Lancashire issues

April 2nd 2019

36,805,512

36,778,298

27,214

Lancashire issues

01 October 2019

37,685,845

37,688,895

-3,050

 

01 December 2019

38,114,460

38,128,991

-14,531

HEF & SAL

01 January 2020

38,273,209

38,278,614

-5,405

HEF & SAL

01 February 2020

38,478,076

38,466,490

11,586

HEF & SAL

 

The differences are gradually being sorted.
I have 2 issues at the moment that are being sorted.
One to do with the Parms issue which I hope will be resolved by the next upload .
 

The other one I am in the middle of writing about as it is a bit more complicated.
See picture below from FC2.  Something a bit wrong there.
Looks like someone has been trying to do an amendment or what???
Whatever has caused is it does not match FC1 list as that is OK.
So how come a PARMS file is different between them both?
 

 

FreeCEN Two 

 

This looks like someone is trying to Edit 4 PIECE numbers  in the FC2 PARMS Online?
PIECE numbers HO511971 to HO511974 1851 Gloucestershire   I could be wrong.
(Copy of the same PIECE numbers in FreeCEN Ones PARM is further down)

 

1971 edit

Guyting

Lower Guyting, Alderton, Beckford, Bishops Cleeve, Bredon, Buckland, Charlton Abbots, Didbrook, Dumbleton, Great Washbourne, Guyting Power, Hailes, Hawling, Hornileazow, Overbury, Prescott, Rowell or Roel, Snowshill, Stanley Pontlarge, Stanton, Stanway, Sudeley Manor, Temple Guiting, Toddington, Winchcomb, Wormington

edit

Winchcomb

Abbey Demesnes, Alderton, Alstone, Bangrove, Barton, Beckford, Bredon, Buckland, Bushops Cleeve, Cartlet, Charlton Abbots, Coates, Cockbury, Corndean, Coscomb, Cutsdean, Didbrook, Didcote, Dixton, Dumbleton, Farmcote, Ford, Frampton, Gotherington, Grafton, Great Washbourne, Greet, Gretton, Guyting Grange, Guyting Power, Hailes, Hawling, Hornileazow, Kineton, Langley, Laverton, Little Washbourne, Naunton, Overbury, Pinnock and Hyde, Postlip, Prescott, Rowell or Roel, Snowshill, Southam Brock'pton, Stanley Pontlarge, Stanton, Stanway, Sudeley Manor, Taddington, Temple Guiting, Toddington, Winchcomb, Wood Stanway, Woodmancote, Wormington, Wormington Grange

1972 edit

Charlton Kings

Badgeworth, Charlton Kings, Cowley, Cubberley, Elmstone Hardwick, Great Shurdington, Leckhampton, Prestbury, Staverton, Swindon, Up Hatherley, Witcombe Magna

Error (not unique)

edit

Cheltenham

Badgeworth, Bentham, Charlton Kings, Cowley, Cubberley, Elmstone Hardwick, Great Shurdington, Leckhampton, Little Shurdington, Little Witcombe, Prestbury, Staverton, Swindon, Uckington, Up Hatherley, Witcombe Magna

Error (not unique)

1973 edit

Cheltenham

Alstone, Arle, Cheltenham, Naunton, Sandford, Westhall

edit

Cheltenham

Cheltenham

1974 edit

Deerhurst

Ashchurch, Bishops Cleeve, Boddington, Bredon, Chaseley, Deerhurst, Elmstone Hardwicke, Forthampton, Hasfield, Kemerton, Leigh, Overbury, Oxenton, Pendock, Tewkesbury, Tirley, Treddington, Twining, Walton Cardiff, Woolstone

edit

Deerhurst

Leigh, Oxenton, Addlestrop, Aylsworth, Bledington, Bourton-on-the-Water, Broadwell, Church Iccomb, Clapton-on-the-Hill, Condicote, Daylesford, Donnington, Evenlode, Eyford, Great Barrington, Great Rissington, Harford, Iccomb, Little Rissington, Longborough, Lowel Swell, Lower Slaughter, Maugersbury, Naunton, Notgrove, Oddington, Sezincote Seas'ct, Stow-on-the-Wold, Upper Sell, Upper Slaughter, Westcote, Wick Rissington

edit

Tewkesbury

Apperley Whit'fld, Ashchurch, Aston-upon-Carron, Bishops Cleeve, Boddington, Bredon, Bredon Village, Chaseley, Conderton, Deerhurst, Deerhurst Walton, Elmstone Hardwicke, Evington, Fiddington Natton, Forthampton, Hardwick with Mitton, Hasfield, Haw, Kemerton, Kinsham, Leigh, Northway and Newton, Norton by Bredon, Overbury, Oxenton, Pamington, Pendock, Southwick with Park, Stoke Orchard, Teddington, Tewkesbury, The Mythe, Tirley, Treddington, Twining, Walton Cardiff, Westmancote, Woolstone

 

 

FreeCEN One   This is FreeCEN Two and nothing wrong with it.

HO107/1971

Guyting

Lower Guyting , Alderton , Beckford , Bishops Cleeve , Bredon , Buckland , Charlton Abbots , Didbrook , Dumbleton , Great Washbourne , Guyting Power , Hailes , Hawling , Hornileazow , Overbury , Prescott , Rowell or Roel , Snowshill , Stanley Pontlarge ,

HO107/1972

Charlton Kings

Badgeworth , Charlton Kings , Cowley , Cubberley , Elmstone Hardwick , Great Shurdington , Leckhampton , Prestbury , Staverton , Swindon , Up Hatherley , Witcombe Magna

HO107/1973

Cheltenham

Cheltenham

HO107/1974

Deerhurst

Ashchurch , Bishops Cleeve , Boddington , Bredon , Chaseley , Deerhurst , Elmstone Hardwicke , Forthampton , Hasfield , Kemerton , Leigh , Overbury , Oxenton , Pendock , Tewkesbury , Tirley , Treddington , Twining , Walton Cardiff , Woolstone

 

Not sure who to raise it with first, Vino to look at it and see if she can fix it  or Kirk.?

Or both?

Will sort it out after the weekend.

**Comment by PatReynolds** [comment] 2020-02-21 16:58
On Tue, 18 Feb, 15:35 Brenda email >Pat and Kirk
I will try to explain my side of things from a FC1 point of view.
Hopefully between us we might come up with a plan!

 

If we got Kirk to remove the duplicates with the numerical addition on them from the  Census Place on FC2 without removing them from the Parms file (See Transcription Page) on FC2  that would be OK.

Otherwise it will be overridden at the following ‘VLD Update/PARMS update’  as anything we amend on FC1  goes through to FC2 the same, at their next update.

I personally would rather do all the PARMS amendments than have further issues.

When they are all done and I can confirm to you both that FC2 TRANSCRIPTION page matches  the FC1 STATISTICS page. (Eventually anyway)

Hopefully, Kirk might  know a way to ensure that the Census Place names like this one for Netherbury as an example, can be removed without upsetting the ‘PARMS Detail’
“Looks like duplications with extra numerical detail”  on the SEARCH PAGE.
Not knowing how that side works, it is only a thought! But that would only cover FC2 I still have to amend for FC1!


Anyway, I am gradually amending the PARMS that have these numbers alongside in the Place Name.
Thankfully it appears at the moment to relate to the 1871 Census.
There are 2 exception being Wiltshire 1861 and Dorset 1841.which have a number in front of the ‘Place’

Wiltshire – 1861 / RG9 Information     2 examples. https://www.freecen.org.uk/freecen_coverage/WIL#1861
 

Piece

Place

Comprising

1268 edit

1 HIGHWORTH

HIGHWORTH HAMLET, WESTROP HAMLET, SEVENHAMPTON, SOUTH MARSTON, BROAD BLUNSDON, CASTLE EATON, BLUNSDON ST ANDREW, RODBORNE CHENEY

1269 edit

1 HIGHWORTH

RODBORNE CHENEY, INGLESHAM, HIGHWORTH (pt), EASTROP HAMLET, FRESDON HAMLET, HANNINGTON, STANTON-FITZWARREN, STRATTON ST MRGART

 
6.     Dorset – 1841 / HO107 Information   Just 3 examples
 

289 edit

Shaston E Division

290 edit

Shaston W Division

291 edit

Sherborne Division

 

Dorset being a strange one as you will see from the above example
Do we need names of Places like these examples?
Shaston E Division : Shaston W Division : Sherbourne Division
Can you imagine someone using any of those to search for a ‘Place’?
Why the word ‘Division’ was used I have no idea.
Dorset 1841 also have these ‘Division Names’  as well
I have checked the name on Google as well on none exist only as the first part of the place.

The ones that I have yet to amend the PARMS for are 1871: BRK. CHS. GLS.HRT. SSX. WAR. WOR AND 1851 WIL.

I will let you know when they have all been done and sent to Lemon and have been uploaded.

I hope that makes sense. If you know of an alternative then please let me know.

**Comment by PatReynolds** [comment] 2020-02-21 17:31
I have put pdfs of these emails into FreeCEN / Data documentation

**Comment by PatReynolds** [comment] 2020-04-29 17:45
Duplicate of #89, so closing.

**Closed as completed by PatReynolds** 2020-04-29 17:45 UTC
Labels: bug
