### ISSUE TITLE
Conversion of piece from FC1 to FC2 format creating isolated where census taken entries

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1539] opened 2023-06-13 12:14 UTC
There has been a condition where where census taken has been completed during conversion but the civil parish and ED number have not been repeated. This bug has been there for a long time, but as it was not causing a serious problem I had simply corrected to odd entry that occurred. Ali sent me a query because this bug has caused havoc when converting shipping spreadsheets. It is now obvious that the bug needs addressing as she has many pieces to convert and update.

The condition is probably caused by the coding that addresses the situation where an ED and civil parish is repeated through a FC1 transcription. 

When a civil parish changes within an ED it is being entered in the where census taken field correctly (it was decided that the civil parish would be the default entry on conversions). However the ED number, civil parish are not being entered in the relevant fields. Neither are the hyphens appearing in the other fields in the ED section.

This is occurring in all years.

Geoff

**Comment by geoffj-FUG** [comment] 2023-06-14 10:01
Anne

There were the samples that I said that I would send to you – but I see it came to me via you! Spreadsheet Files sent by email.

RG9_4458x is the original FC1 file as transcribed. You will see the changing of the civil parishes within the ED0#8.

RG9_4459y is where I have amended the spreadsheet so that you can see how it should look. I have only corrected the first 120 rows.

RG9_4459z is the converted spreadsheet that shows you how it actually looks.

The guidelines are that whenever something changes within the ED section then all columns within that section should be completed. The section ends at the flag column.

Geoff

**Comment by AnneV-Learn** [comment] 2023-06-14 12:12
Thanks @geoffj-FUG 
A question - in RG9_4459y (how it should look) the Civil Parish on the first line (Shields Unk) has been used for every record with an enumeration district (rather than using the Civil Parish on the same line of the input file). Is that something that should happen specifically for Shipping data?

**Comment by geoffj-FUG** [comment] 2023-06-15 06:47
Anne

 

If all schedules have exactly the same ED details as the previous schedule, then they are not entered on the spreadsheet.

 

If one or more of the values change then all the fields must be entered.

 

I shouldn’t do changes when tired! I did not do 4459y correctly. I have attached the corrected file.

 

My apologies.

 

Geoff

**Comment by AnneV-Learn** [comment] 2023-06-15 07:00
No prob - could you email the corrected file please - thanks Geoff
A

On 15 Jun 2023, at 07:47, Geoff J ***@***.***> wrote:

﻿

Anne



If all schedules have exactly the same ED details as the previous schedule, then they are not entered on the spreadsheet.



If one or more of the values change then all the fields must be entered.



I shouldn’t do changes when tired! I did not do 4459y correctly. I have attached the corrected file.



My apologies.



Geoff

**Comment by AnneV-Learn** [comment] 2023-06-16 08:55
@Geoff fix deployed to Test3, so Ready for Testing

**Comment by geoffj-FUG** [comment] 2023-06-17 07:00
Anne

 

I have Downloaded 5 files as CSVPro. Some were OK but two have problems. I have attached the output spreadsheets.

RG94492 - Where_census_taken is not populated. A hyphen causes an error. The entry should be Plymouth (the civil parish).

RG94470 has the same issue. Attached.

 

The other files tested were 

RG94442 (see Row 197, the rest looks OK), 

RG94475 (looks OK and has the same change from 0#2 to 0#8 as 4492).

RG94489. (The where_census_taken field was populated correctly in this file but it only has one parish).

 

Geoff

**Comment by AnneV-Learn** [comment] 2023-06-17 07:07
Ok thanks @geoffj-FUG I’ll take another look.

**Comment by AnneV-Learn** [comment] 2023-06-17 08:18
@geoffj-FUG Hmmm - the original issue (that I thought this issue related to) was raised by Ali and related to "**Convert to modern headers and download**":

Her feedback message:
_For EWS files, when I select "Convert to modern headers and download", after line 2 the converted file has civil parishes in the where_census_taken field, and there are no EDs. Very puzzled here._

So that is where I looked and made the code change.

Now looking at the story title etc properly it looks like this is an issue with 'Download file as CSVPro'. 
So is there an issue with both? 
Can you clarify please.

**Comment by geoffj-FUG** [comment] 2023-06-17 09:38
Anne

 

This is a Convert and download as csv issue.

 

What I saw in Ali’s spreadsheets appeared to be a major iteration of what was a minor annoyance in the normal spreadsheets.

 

Geoff

**Comment by AnneV-Learn** [comment] 2023-06-17 12:32
@geoffj-FUG 
There are two separate areas of code for the VLD 'Convert and download as csv' and the CSVProc 'Convert to modern headers and download'. Wrongly or rightly I modified 'Convert to modern headers and download' under this story (to resolve issue originally reported by Ali).
So could you please test that?

I have looked at the the files you reported back on - assuming you used the 'Download file as CSVPro' for VLD files my findings are below.

**RG9_4442**

This is caused by what I consider to be an error in the VLD file - Ecclesiastical Parish is '-' on just these lines! See VLD input values below.
So I think this would have to be resolved during CSVProc validation.![Screenshot 4442.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/91048be7-ef17-43fb-8cf6-85c31b343789)

**RG9_4470**  
Again I think this is caused by errors in the VLD file - Ecclesiastical Parish on **ALL** records is '-'
![Screenshot4470.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/c04b8a99-d4dc-4e25-9c61-d035eb53c75d)

**RG9_4492**

As 4470 above - I think this is caused by errors in the VLD file - Ecclesiastical Parish on **ALL** records is '-'
![Screenshot4492.png](https://images.zenhubusercontent.com/6009aeccd60429cb7008e5d3/2c1bf592-0e4d-42b0-9c8e-aeae8b90974a)

**Comment by geoffj-FUG** [comment] 2023-06-18 06:02
Anne

 

I thought that the where_census_taken was to be populated with the civil parish, not the ecclesiastical parish. The ecclesiastical parish is not always populated, but the civil parish is.

 

Geoff

**Comment by AnneV-Learn** [comment] 2023-06-18 06:48
@geoffj-FUG - Oh perhaps I wasn’t looking at the right field. I’ll re-check.

**Comment by AnneV-Learn** [comment] 2023-06-18 09:46
@geoffj-FUG I was right.  
The current logic for 'Where Census Taken' is that if Ecclesiastical Parish is present and it is not blank it uses that, otherwise it uses the Civil Parish.  
In the test cases highlighted in my previous comment  Ecclesiastical Parish is present and is not blank because it contains a hyphen.
I have just modified the code so that if Ecclesiastical Parish contains a hyphen it is treated as if it were blank. 
I’ll get that modification deployed to Test3 and let you know when you can retest. 
The code relating to 'enumeration_district, civil_parish, eccesiastical_parish, where_census_taken' and how it either 'repeats' or not  is very complicated, so I think it would be advisable to do quite a few tests please Geoff not just EWS data.

**Comment by geoffj-FUG** [comment] 2023-06-18 10:14
Anne

 

I can understand that logic. This is not the logic that was discussed between Kirk and I. It was a toss up as to how we populated the field.

 

However Ecclesiastical Parish will never be blank. If we don’t know the EC then we enter a hyphen. A blank field in the spreadsheet raises an error.

 

Pragmatically the change you propose is fine. You say (I have just modified the code so that if Ecclesiastical Parish contains a hyphen it is treated as if it were blank).

 

You are right – I need to test a few pieces. Once EWS is correct I will find some normal vlds to see how they pan out.

 

Geoff

**Comment by suffolkroots** [comment] 2023-06-19 07:35
This issue refers to "Convert to modern headers and download" in FC2.

FC1 VLD files download as csvpro correctly.

**Comment by AnneV-Learn** [comment] 2023-06-19 07:44
@geoffj-FUG Test3 has now been updated with the change (Ecclesiastical Parish contains a hyphen it is treated as if it were blank), so ready for you to test please.

**Comment by geoffj-FUG** [comment] 2023-06-19 10:18
Anne

 

I am away for a week. I had a quick look and I have some queries (to myself). 

 

I would like to wait to test this until I get home. I can then look at the downloads that I have on my PC.

 

I note Ali’s comment, but the problem is in both downloads. As you say I really need to do some widespread testing on this.

 

Geoff

**Comment by DeniseColbert** [comment] 2023-08-23 08:29
@geoffj-FUG to convert a shipping piece to see if this is still a problem

**Comment by geoffj-FUG** [comment] 2023-08-24 07:33
I have downloaded a big EWS piece and it now looks OK.
We are about to build a EWS PARMS and fix up the civil parishes. Once this is done I will test again. I have shown the Shipping PARMS as a blocker simply as a reminder that this has to be done.

**Comment by DeniseColbert** [comment] 2023-10-18 08:25
Believed to be complete: closing

**Closed as completed by DeniseColbert** 2023-10-18 08:25 UTC
Labels: bug, Ready for User Test
