### ISSUE TITLE
Error when uploading traditional csv file (VLDs)

### ISSUE THREAD

**Issue by AnneV-Learn** [FreeUKGen/FreeCENMigration#1522] opened 2023-04-25 20:26 UTC

**Comment by AnneV-Learn** [comment] 2023-04-25 20:30
Serious error message when uploading  1871 pieces from SRY 1871 reported by @geoffj-FUG

**Comment by AnneV-Learn** [comment] 2023-04-25 20:44
@geoffj-FUG I have found a bug. It is looking for the column header field for the ecclesiastical district to be in upper case ie 'ED' not 'ed'. 
So the _temporary_ workaround is to edit the csv file to make it 'ED'. It will then process correctly identifying it as a traditional file. After the initial processing the '**Convert to modern headers and download**' button will appear for the file. Click this and the use '**Replace**' to load that converted file.

I'll fix the bug.

**Comment by AnneV-Learn** [comment] 2023-04-25 20:50
@geoffj-FUG The bug fix is now ready for testing on Test3

**Comment by geoffj-FUG** [comment] 2023-04-26 00:15
Thanks Anne

 

I have let the Coordinators know.

 

Geoff

**Comment by DeniseColbert** [comment] 2023-05-03 08:05
@geoffj-FUG could you test the bug fix please?

**Comment by geoffj-FUG** [comment] 2023-05-10 06:53
Anne

The problem is bigger than that. 

I have just had a piece converted from vld to FC1 Traditional format. FCTools does not run on 64 bit machines, though parts of it does. The piece that I had converted was done using a sub-utility called dat to csv. The conversion ran but there are many problems in the header row.
Given that the last of the FC1 pieces is being uploaded I see no value in trying to resolve the broader problem. The problem is out of date software.
As far as the ED problem is concerned we can deploy the bug fix. This seems to be the most prominent issue. It is a header row problem so should have been fixable by copying a good header row into the spreadsheet. That is how we fix the problem with corrupted headers in FC2.
Once this is done we should no longer try to fix problems in a part of the system that will not be used beyond the next few months once all FC1 vld files have been uploaded.
As an aside I am finding it difficult to find anybody who has a PC that can run FCTools for me. Everything has gone 64 bit!
Geoff

**Comment by DeniseColbert** [comment] 2023-05-31 08:08
deployed, closing

**Closed as completed by DeniseColbert** 2023-05-31 08:08 UTC
Labels: Ready for Deployment
