### ISSUE TITLE
Hyperlink the Census Place names to a listing of everyday city district, towns, villages, etc

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#599] opened 2019-02-16 13:36 UTC
A useful addition to the Search Detail/results table would be to hyperlink the Census Place names (final column in table) to a listing of everyday city district, towns, villages, etcetera.

**Comment by Captainkirkdawson** [comment] 2021-12-05 22:50
Duplicate of #439

**Closed** 2021-12-05 22:53 UTC
Labels: Feedback, Place
