### ISSUE TITLE
Link from Place/Parish to GENUKI in results screen

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeCENMigration#657] opened 2019-03-26 11:09 UTC
Link to GENUKI (or similar) map from Place, and/or Civil Parish and/or Ecclesiastical Parish in result for household

E0: U3: S2: C6: P11

**Comment by Captainkirkdawson** [comment] 2019-03-26 13:38
It should be noted that place within a piece has current information  that provides links to google maps for the majority of pieces. The edit of a piece provides the ability to add  or change the specific map location.

**Comment by Captainkirkdawson** [comment] 2021-12-05 22:55
Duplicate of https://app.zenhub.com/workspaces/freecen-5cb4e56573d7e234297de6c6/issues/freeukgen/freecenmigration/439

**Closed by Captainkirkdawson** 2021-12-05 22:55 UTC
Labels: ready, Could have, User Experience, Place, P11
