### ISSUE TITLE
Use of '- instead of - in legacy files

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#913] opened 2020-07-15 14:49 UTC
@geoffj-FUG said
 I have a query
I have been converting old pieces this evening and uploading them.
Because of the predilection of Excel to change a – to a formula instructions were given to put a ‘ before the -. (i.e. ‘_) to prevent the formula occurring, as it changed the cell to a text cell.
Does this affect uploading on FreeCEN2?
I ask because in the example below all the ‘- have come out as errors. See Row 1661 et seq.
I don’t know how this works on upload so I can’t make a decision about how these should be handled.

**Comment by Captainkirkdawson** [comment] 2020-07-15 14:50
Absolutely the marital status is a single character not 2. 

Why was this done? the column could have been declared as text or the entry quoted

What do you want to do?

Does it only apply to Marital? What about sex it can also be -

**Comment by Captainkirkdawson** [comment] 2020-07-15 14:51
Kirk

 

It applies to them all

 

It was done because transcribers kept getting formulae in their spreadsheets whilst they were transcribing.

 

.csv files do not retain their formatting. They lose it when the file is closed. If the column was designated text or number it gets removed.

 

I will need to apply some grey matter to this one.

 

I will also have to start making some notes about legacy files.

 

Geoff

**Comment by geoffj-FUG** [comment] 2020-07-15 22:43
Kirk

 

I have included a note about not using ‘- in the instructions for FreeCEN2.

 

However the problem will need to be resolved with legacy files. 

 

Still thinking about that. I have noted the Story in my Testing CSVProc Record for follow up.

**Comment by geoffj-FUG** [comment] 2020-09-27 10:48
My solution for legacy files - I have amended the Handbook instructions for uploading legacy files to include a Replace All '- with -.
That means that the problem is fixed before upload.
This item may be closed.
Geoff

**Closed as completed** 2020-09-27 14:02 UTC
