### ISSUE TITLE
revisit places again

### ISSUE THREAD

**Issue by dougkdev** [FreeUKGen/FreeCENMigration#165] opened 2016-10-31 15:07 UTC
NB: in this description, place means ANY geographic entity / substitute: Scotland, County Durham, SOM, Parts of Holland, Whitby, Clifton, Abertawe, Glaschu, Lower Slaughter and Blubberhouses are all places.  

We have been through multiple versions of how to handle places, each time receiving the feedback that it isn't what is wanted.  How places are desired to be handled needs to be very clearly defined as it is an integral part of the data model, search functionality, and database indexes.

This issue is part of the Place Epic.
Components:
understand/document what data we hold about place (in progress - documented in this issue - awaiting response from Brenda)
understand/document what we do with the data we transcribe about place, e.g. create indexes, convert to a different form, add a standardized form - (in progress, partly documented in this issue, partly in issues #492, #378, #533 and #534 for validation, in issues #492 and #402 for proofreading, #534, #590, #489, and #488 for transcription)
understand the issues with place (e.g. as non-stable geographic entities) (documented in this issue)
understand how users wish to search using place data (#52 is the epic, issue #225 for birth place, #155 for census place) 
understand what/how users wish to see place data presented in search results (#52 is the epic)
understand what/how users wish to see place data presented in detailed search results (#52 is the epic)
understand what/how users wish to see place data presented elsewhere in FC2 (#52 is the epic)
write stories for the missing links.

Economic 8, urgency 6, strategy 8, effort 5: P27

**Comment by PatReynolds** [comment] 2016-11-08 08:51
I think that we already capture/need to handle the various places, ie.
Counties, Census districts, CofE parishes, ship's names (are there any others like CofE parishes and ships names which are standardised?), and multitude of names that are recorded as place of birth 
What we don't know is (and is story #52) how people will want to search, using some, many or all of these types of place names.  So until we do, we can't build the search.
What more is needed to be known at this point?

**Comment by dougkdev** [comment] 2016-11-29 22:49
I agree with you, Pat, we need to know how people will search in order to define the data model to support the search. I don't think more information is needed right now, but the place data model is a significant piece that needs a clear definition to come out of #52.

Ben did a couple of revisions of places before he turned it over to me.  When he used the district or parish names as the places, most of the feedback was that it was wrong because it was different than FC1.  I changed it to be the same as FC1, and it is wrong again because it doesn't handle the problems that people didn't like in how FC1 handled places.

There are some issues we now know that users would like handled differently than FC1 due to feedback received by Brenda. For one, several census pieces are listed under one county, even though there is actually some information in those pieces from an entirely different county.  For example, in 1891 NTT pieces 2715-2716 have several places that are actually in LIN. That information then appears in searches for the county the piece belongs to and not in searches for counties that the data is actually for.  For another, places can't be selected unless they happen to be the places as listed in the PARMS.DAT files (representing the places listed by the National Archives / GRO as a summary of places for each piece). A recent example that Brenda addressed with one user is Lincs Spalding 1841 (HO107/610) listed as place "Part Holland".

I think that the way in which places are searched needs to be more flexible to handle the places we have from the actual transcriptions in addition to those listed in the PARMS.DAT files.  Instead of choosing a county and then a place within that county (which may actually be in the wrong county because the piece spans multiple counties, or confusing because place names differ from year to year or vary spelling, etc.), perhaps the interface should be more like people are accustomed to on google maps, etc.  The user types the place they want to search for as free-form text (could be a parish, a district, or combination of those, for example) and the site auto-suggests places similar to what they are typing.

**Comment by PatReynolds** [comment] 2017-05-11 11:30
Just checking that this is the conversation that @benwbrum was referring to in #167 and #242 - please let me know if you know more about the feedback and please send it to me.

**Comment by PatReynolds** [comment] 2018-10-19 14:41
I have drafted a document on 'how to solve the London issue' - https://docs.google.com/document/d/1Ng6nIm089tBdNB-npsHj5DB_cpORg3VbD-LsDDrPXYA/edit?usp=sharing  comments and thoughts, please.

**Comment by richpomfret** [comment] 2018-10-24 14:46
@FreecenBren to have a look.

**Comment by DeniseColbert** [comment] 2019-02-21 09:53
@FreecenBren Pat's asked if you could take a look at the doc above and raise questions / suggest changes for her return?

**Comment by benwbrum** [comment] 2019-05-01 14:55
Pat to talk to @richardofsussex on this.

**Comment by PatReynolds** [comment] 2019-05-02 09:03
Contacted Richard 2/5/2019

**Comment by richpomfret** [comment] 2019-06-19 14:22
Let's discuss during next roadmap meeting on Monday.

**Comment by Captainkirkdawson** [comment] 2019-06-25 15:01
Brenda asked:
Each record has a ‘Birth Place column’ and of course a ‘Birth Place’
Is it , or would it be possible, to create/obtain a list of all these Birth Places from the FreeCEN Database?
Assuming Brenda ment the the individual record in the request :
There are actually 5 fields that appear to be associated with birth_place for an individual. 

  field :birth_place, type: String
  field :verbatim_birth_county, type: String
  field :verbatim_birth_place, type: String
  field :birth_place_flag, type: String

It would appear that the verbatim_birth field contents are often(always?) the same as the birth_ field contents. I know not why there are the 2 sets of fields
I do not know the purpose of the  birth_place_flag 

WRT to the specific question. 

Currently it would be extremely time consuming  to go through the Freecen1VldEntry/individual collection as there are no indexes and it would mean processing all 37 million+ records

If it was an important request I would first create indexes on the fields and then it would be straight forward.

**Comment by Captainkirkdawson** [comment] 2019-06-25 15:12
Thinking about the question I did a little more research.
The search record against which we search contains the census place identifier as well as the county.
It also contains the birth_chapman_code which I assume is extracted from the birth_county.
It does not contain any field associated with birth_place.
The birth_chapman_code is not indexed.

**Comment by FreecenBren** [comment] 2019-06-25 18:12
Index of CHP

The Chapman Code is added at the Transcription CSV stage by the transcriber
from the Census images.
It therefore goes through all the stages and into the final VLD.

If any CHP is not from the accepted list, (example. Typed incorrectly) and
is not picked up by the any of the FreeCEN stages of,
1. CSV
2. CSVCHECK,
3. DAT
4. CHE
5. FCTOOLS,
6. finally to a VLD, then the upload will throw it our as an error.
We then have to do an amended VLD.
In FC1 there must be a check for it to throw out the error.

Of course FC2 will be able to do that, when we get to that stage.

**Comment by richpomfret** [comment] 2019-07-03 14:54
Let's go ahead and do this.

**Comment by PatReynolds** [comment] 2019-07-18 16:49
field :birth_county, type: String
field :birth_place, type: String
field :verbatim_birth_county, type: String
field :verbatim_birth_place, type: String
field :birth_place_flag, type: String
@FreecenBren can you confirm that the verbatim_birth_county/place is twys, and the birth_county/place is what is picked from an authorised/standardized list?

**Comment by richpomfret** [comment] 2019-12-04 17:32
@PatReynolds let's discuss when you return and move this out of progress if it's not moving forward.

**Comment by PatReynolds** [comment] 2020-02-05 11:40
Checked with Brenda 5/2/2020.

**Comment by PatReynolds** [comment] 2020-02-05 17:36
@Captainkirkdawson to get distinct entries (as done for Unique names) of each field.

**Comment by Captainkirkdawson** [comment] 2020-02-06 01:40
Wrote the rale task. Ran on test3. Results were interesting. County information follows
Birth County 294 values 
["ABD", "OUC", "UNK", "IRL", "ENG", "BAN", "KCD", "ANS", "OVF", "WAL", "OVB", "NAI", "ARL", "FIF", "NFK", "ELN", "MLN", "MOR", "WIG", "PER", "LKS", "INV", "ROC", "RFW", "SUT", "AYR", "OKI", "STI", "IOM", "KEN", "ROX", "CLK", "IOW", "KKD", "MDX", "CAI", "DFS", "GLS", "BEW", "TYR", "WIC", "SHI", "CUL", "YKS", "LIM", "GSY", "NBL", "DUR", "LDY", "SCT", "DEV", "HAM", "CON", "SFK", "PEE", "DNB", "ESS", "WLN", "KRS", "WRY", "MER", "GAL", "LIN", "MOG", "DBY", "JSY", "DOW", "NRY", "SEL", "NTH", "SRY", "CAV", "COR", "STS", "SSX", "BKM", "SAL", "SOM", "CLA", "BRK", "LAN", "TIP", "DON", "LND", "CHI", "OXF", "MAY", "MON", "CHS", "GLA", "DUB", "ARM", "WAR", "ANT", "ROS", "OFF", "SLI", "ERY", "DOR", "FER", "NTT", "KIK", "MEA", "LET", "HRT", "KER", "BUT", "WAT", "LOU", "LEI", "WOR", "KID", "LEX", "WEM", "HEF", "CAR", "WEX", "FLN", "WIL", "PEM", "WES", "LOG", "BDF", "CAM", "ALD", "CAE", "HUN", "DEN", "MGY", "RAD", "AGY", "CMN", "CGN", "BRE", "RUT", "SRK", "\u0000\u0000\u0000", "LEN", "NBo", "NBl", "NWi", "S-", "NPr", "NKe", "SCo", "NTo", "NHe", "NRa", "NCh", "NTy", "NPa", "NSt", "SKi", "L-", "LWe", "NFa", "NWe", "NWa", "NSh", "NDa", "NRu", "T-", "NOv", "NDe", "NBu", "KHi", "NLe", "NHa", "NLi", "NMa", "N-", "NHo", "NEu", "BWe", "SDe", "MPo", "NSa", "NTu", "LCa", "SLe", "SHu", "NWh", "NBe", "D-", "NHi", "YDe", "NAi", "NCl", "SSt", "NRo", "NDu", "NAs", "MBa", "SCl", "SRa", "NCa", "SHi", "SBi", "SMa", "NWo", "NSu", "NSk", "NTw", "NBr", "SHo", "SPe", "NBi", "RNu", "SNa", "NGr", "NAt", "NCr", "NCo", "SSe", "SGr", "RCy", "NGo", "NMi", "XLo", "NLo", "ILe", "NSo", "BHo", "SRi", "NLa", "LPe", "SWi", "NPe", "RCr", "SHy", "SEt", "NAc", "NEc", "NRi", "NIn", "SKe", "SMi", "NPo", "NCu", "NBa", "NFe", "V-", "RRu", "NAd", "SBr", "RBi", "NMo", "SWa", "NPi", "LSt", "NEd", "SDa", "NGa", "NWr", "YLu", "SSc", "NGl", "NKi", "LBo", "LDu", "SFl", "SYo", "SEg", "LCo", "LKi", "NNe", "NPl", "NUl", "YMa", "SDu", "SMe", "SJo", "M-", "LBe", "TUp", "LNo", "LMa", "FHa", "SHa", "TSu", "LWh", "LKe", "SBa", "SSa", "FBe", "SEd", "TDu", "NDi", "SLY", "LDN", "SCO", "LON", "BDS", "ATH"]
Verbatim Birth County 294 values 
["ABD", "OUC", "UNK", "IRL", "ENG", "BAN", "KCD", "ANS", "OVF", "OVB", "WAL", "NAI", "ARL", "FIF", "NFK", "ELN", "MLN", "MOR", "WIG", "PER", "LKS", "INV", "ROC", "RFW", "SUT", "AYR", "STI", "IOM", "KEN", "ROX", "CLK", "IOW", "KKD", "MDX", "CAI", "OKI", "GLS", "BEW", "TYR", "WIC", "SHI", "CUL", "YKS", "LIM", "GSY", "DFS", "NBL", "DUR", "LDY", "SCT", "DEV", "HAM", "CON", "SFK", "PEE", "ESS", "WLN", "KRS", "WRY", "DNB", "GAL", "LIN", "MOG", "DBY", "JSY", "DOW", "NRY", "SEL", "SRY", "CAV", "COR", "STS", "SSX", "BKM", "LEI", "SAL", "SOM", "CLA", "BRK", "LAN", "TIP", "DON", "LND", "CHI", "OXF", "MAY", "MON", "CHS", "GLA", "DUB", "ARM", "WAR", "ANT", "ROS", "OFF", "SLI", "ERY", "DOR", "FER", "NTT", "KIK", "MEA", "LET", "HRT", "KER", "BUT", "WAT", "LOU", "WOR", "LEX", "KID", "WEM", "HEF", "NTH", "CAR", "WEX", "FLN", "WIL", "PEM", "WES", "LOG", "MER", "BDF", "CAM", "ALD", "CAE", "HUN", "DEN", "MGY", "RAD", "AGY", "CMN", "CGN", "BRE", "RUT", "SRK", "\u0000\u0000\u0000", "LEN", "NBo", "NBl", "NWi", "S-", "NPr", "NKe", "SCo", "NTo", "NHe", "NRa", "NCh", "NTy", "NPa", "NSt", "SKi", "L-", "LWe", "NFa", "NWe", "NWa", "NSh", "NDa", "NRu", "T-", "NOv", "NDe", "NBu", "KHi", "NLe", "NHa", "NLi", "NMa", "N-", "NHo", "NEu", "BWe", "SDe", "MPo", "NSa", "NTu", "LCa", "SLe", "SHu", "NWh", "NBe", "D-", "NHi", "YDe", "NAi", "NCl", "SSt", "NRo", "NDu", "NAs", "MBa", "SCl", "SRa", "NCa", "SHi", "SBi", "SMa", "NWo", "NSu", "NSk", "NTw", "NBr", "SHo", "SPe", "NBi", "RNu", "SNa", "NGr", "NAt", "NCr", "NCo", "SSe", "SGr", "RCy", "NGo", "NMi", "XLo", "NLo", "ILe", "NSo", "BHo", "SRi", "NLa", "LPe", "SWi", "NPe", "RCr", "SHy", "SEt", "NAc", "NEc", "NRi", "NIn", "SKe", "SMi", "NPo", "NCu", "NBa", "NFe", "V-", "RRu", "NAd", "SBr", "RBi", "NMo", "SWa", "NPi", "LSt", "NEd", "SDa", "NGa", "NWr", "YLu", "SSc", "NGl", "NKi", "LBo", "LDu", "SFl", "SYo", "SEg", "LCo", "LKi", "NNe", "NPl", "NUl", "YMa", "SDu", "SMe", "SJo", "M-", "LBe", "TUp", "LNo", "LMa", "FHa", "SHa", "TSu", "LWh", "LKe", "SBa", "SSa", "FBe", "SEd", "TDu", "NDi", "SLY", "LDN", "SCO", "LON", "BDS", "ATH"]
Birth County NOT in Verbatim Birth County 0 values 
[]
Verbatim Birth County NOT in Birth County 0 values 
[]
Says they are identical
BUT THERE ARE A SIGNIFICANT NUMBER THAT ARE NOT CHAPMAN CODES
MAKES ME WONDER ABOUT OUR BIRTH COUNTY SEARCH VALIDITY
Given what I found here I ran a quick test of the Birth Chapman Code in the search record on test3. This has 176 distinct entries BUT there are only 155 Valid Chapman Codes for CEN and some are clearly in error. e.g.         "-"  "\u0000\u0000\u0000"  "`" and I suspect there are others.
Regardless of the original purpose of this work it need to be run on production and further investigation conducted as there are clear quality issues here. Will start a different story for that aspect.

**Comment by Captainkirkdawson** [comment] 2020-02-06 01:46
The birth place results are also interesting. Will not give the arrays as they are too large. I have them if someone wants them.
Birth Place 388,033 values 
Verbatim Birth Place 468,433 values 
Birth Place NOT in Verbatim Birth Place 5,644 values 
Verbatim Birth Place NOT in Birth Place 86,044 values 
If it was of value we could break these latter numbers down by county

**Comment by PatReynolds** [comment] 2020-02-06 10:21
Do abbreviations (such as Mkt for Market,  Gt. for Great and Lwr for Lower typically occur in the Birth place or the Verbatim Birth Place)?

**Comment by Captainkirkdawson** [comment] 2020-02-06 17:38
@PatReynolds not sure of the purpose in your question but the answers are
Mkt Birth ;63 Verbatim 85; in birth but NOT verbatim 1; in verbatim but NOT birth 23
Gt. Birth ;191 Verbatim 236; in birth but NOT verbatim 1; in verbatim but NOT birth 46
Gt Birth ;647 Verbatim 821; in birth but NOT verbatim 2; in verbatim but NOT birth 176
Lwr Birth ;43 Verbatim 47; in birth but NOT verbatim 3; in verbatim but NOT birth 4

The key information for me is that there are Birth Place 388,033 values and Verbatim Birth Place 468,433 values This tells that as a free form field there are vast numbers of variations e.g. Was use is a Place called St Ann in Yorkshire
A sample follows

[sample.log](https://github.com/FreeUKGen/FreeCENMigration/files/4166801/sample.log)

**Comment by PatReynolds** [comment] 2020-02-18 12:03
Thanks, Kirk, that's useful (verbatim is confirmed as the TWYS field).
I' can't open a .log file, unfortunately.  
I think that the development of a new validation tool (and new list of approved places) would resolve the St Ann. 
The answer for St Ann to be no:
![image](https://user-images.githubusercontent.com/6338822/74734125-d7810780-5245-11ea-983d-6ac9b05cbdcd.png)
(but if this is where someone said they were born - perhaps mistaking 'baptism' for 'birth') then that's what we have to use.

**Comment by FreecenBren** [comment] 2020-02-18 16:38
Please note. If we want to be correct.
Many people live in St Ann’s ( Prince Harry should know as he often visits)
Also I went to school there as well.

St Ann’s is in Nottingham  and has always been St Ann’s. (With an ‘s’)
St Ann's is a large district of the city of Nottingham, in the English
ceremonial county of Nottinghamshire.
The development of the St Ann's actually began as early as 1750 when
Charles Morley was the  Sheriff in 1737-8.
It is still known by that name today.

Brenda

**Comment by Captainkirkdawson** [comment] 2020-02-19 23:18
Am experimenting with text indexes on the birth_place field. Very interesting. 

> db.freecen_individuals.find({ $text: { $search: "\"st ann\""},birth_county: "NTT"}).count()  84
> db.freecen_individuals.find({ $text: { $search: "\"st. ann\""},birth_county: "NTT"}).count()  6
> db.freecen_individuals.find({ $text: { $search: "\"saint ann\""},birth_county: "NTT"}).count()  0

> db.freecen_individuals.find({ $text: { $search: "\"st ann's\""},birth_county: "NTT"}).count()  8

An example of those picked up by the first st ann
 "_id" : ObjectId("5904473ce9379091b1e97ca8"),
        "birth_county" : "NTT",
        "birth_place" : "St Ann's",
        "verbatim_birth_county" : "NTT",
        "verbatim_birth_place" : "St Ann's"
}
{
        "_id" : ObjectId("5904473ae9379091b1e97987"),
        "birth_county" : "NTT",
        "birth_place" : "St Ann's",
        "verbatim_birth_county" : "NTT",
        "verbatim_birth_place" : "St Ann's"
}
{
        "_id" : ObjectId("59044644e9379091b1e84a40"),
        "birth_county" : "NTT",
        "birth_place" : "St Anns",
        "verbatim_birth_county" : "NTT",
        "verbatim_birth_place" : "St Anns"
}
{
        "_id" : ObjectId("59044644e9379091b1e84a3f"),
        "birth_county" : "NTT",
        "birth_place" : "St Anns",
        "verbatim_birth_county" : "NTT",
        "verbatim_birth_place" : "St Anns"
}
{
        "_id" : ObjectId("5904455ee9379091b1e749f4"),
        "birth_county" : "NTT",
        "birth_place" : "St Annes",
        "verbatim_birth_county" : "NTT",
        "verbatim_birth_place" : "St Annes"
}
{
        "_id" : ObjectId("59044556e9379091b1e741de"),
        "birth_county" : "NTT",
        "birth_place" : "St Ann",
        "verbatim_birth_county" : "NTT",
        "verbatim_birth_place" : "St Ann"

**This shows that the search word acts as a stub ie ann finds ann ann's annes 
The following is even more interesting**

> db.freecen_individuals.find({ $text: { $search: "\"st len\""}}
{
        "_id" : ObjectId("59032e46e9379091b1ddfca4"),
        "birth_county" : "LND",
        "birth_place" : "Shoreditch St Len",
        "verbatim_birth_county" : "LND",
        "verbatim_birth_place" : "Shoreditch St Len"
}
{
        "_id" : ObjectId("59f23b99e937906e99329da2"),
        "birth_county" : "SSX",
        "birth_place" : "St Leonards On Sea",
        "verbatim_birth_county" : "SSX",
        "verbatim_birth_place" : "St Lenords"
}
{
        "_id" : ObjectId("590671c3e9379091b1f30fcf"),
        "birth_county" : "AYR",
        "birth_place" : "St Quivox",
        "verbatim_birth_county" : "AYR",
        "verbatim_birth_place" : "St Lennox"
}
{
        "_id" : ObjectId("5905b1a4e9379091b16ce87c"),
        "birth_county" : "SSX",
        "birth_place" : "St Lenards",
        "verbatim_birth_county" : "SSX",
        "verbatim_birth_place" : "St Lenards"
}
{
        "_id" : ObjectId("5905b1a4e9379091b16ce87a"),
        "birth_county" : "SSX",
        "birth_place" : "St Lenords",
        "verbatim_birth_county" : "SSX",
        "verbatim_birth_place" : "St Lenords"
}
{
        "_id" : ObjectId("5905099fe9379091b11354b5"),
        "birth_county" : "SSX",
        "birth_place" : "St Leonards",
        "verbatim_birth_county" : "SSX",
        "verbatim_birth_place" : "St Lenards"
}
{
        "_id" : ObjectId("5904f5b1e9379091b1073060"),
        "birth_county" : "SSX",
        "birth_place" : "St Leonards",
        "verbatim_birth_county" : "SSX",
        "verbatim_birth_place" : "St Lenards"
}
{
        "_id" : ObjectId("5904cc54e9379091b1d3db74"),
        "birth_county" : "SSX",
        "birth_place" : "St Leonards",
        "verbatim_birth_county" : "SSX",
        "verbatim_birth_place" : "St Lenards"
}
{
        "_id" : ObjectId("5904cc4fe9379091b1d3ce5d"),
        "birth_county" : "SSX",
        "birth_place" : "St Leonards",
        "verbatim_birth_county" : "SSX",
        "verbatim_birth_place" : "St Lenords"
}
{
        "_id" : ObjectId("5904cc4fe9379091b1d3ce56"),
        "birth_county" : "SSX",
        "birth_place" : "St Leonards",
        "verbatim_birth_county" : "SSX",
        "verbatim_birth_place" : "St Lenords"
}
{
        "_id" : ObjectId("59047519e9379091b1451cf6"),
        "birth_county" : "BEW",
        "birth_place" : "St Lenords",
        "verbatim_birth_county" : "BEW",
        "verbatim_birth_place" : "St Lenords"
}
{
        "_id" : ObjectId("5903db68e9379091b103b876"),
        "birth_county" : "HEF",
        "birth_place" : "St Weonards",
        "verbatim_birth_county" : "HEF",
        "verbatim_birth_place" : "St Lenords"
}
{
        "_id" : ObjectId("59037f72e9379091b1fe1866"),
        "birth_county" : "LEI",
        "birth_place" : "St Lenords",
        "verbatim_birth_county" : "LEI",
        "verbatim_birth_place" : "St Lenords"
}
{
        "_id" : ObjectId("59034720e9379091b13392e7"),
        "birth_county" : "MDX",
        "birth_place" : "St Leonards",
        "verbatim_birth_county" : "MDX",
        "verbatim_birth_place" : "St Lenords"
}
{
        "_id" : ObjectId("5902e10fe9379091b1b97929"),
        "birth_county" : "SCT",
        "birth_place" : "St Lenneck",
        "verbatim_birth_county" : "SCT",
        "verbatim_birth_place" : "St Lenneck"
}
{
        "_id" : ObjectId("5902dbc2e9379091b1a4d8d7"),
        "birth_county" : "DEV",
        "birth_place" : "St Lenards",
        "verbatim_birth_county" : "DEV",
        "verbatim_birth_place" : "St Lenards"
}
{
        "_id" : ObjectId("5902b0eee9379091b1f98102"),
        "birth_county" : "CON",
        "birth_place" : "St Lennen",
        "verbatim_birth_county" : "CON",
        "verbatim_birth_place" : "St Lennen"
}
{
        "_id" : ObjectId("5902b0eee9379091b1f98100"),
        "birth_county" : "CON",
        "birth_place" : "St Lennen",
        "verbatim_birth_county" : "CON",
        "verbatim_birth_place" : "St Lennan"
}
{
        "_id" : ObjectId("5906ab35e9379091b11c4fa8"),
        "birth_county" : "WIL",
        "birth_place" : "Blunsdon St Lenards",
        "verbatim_birth_county" : "WIL",
        "verbatim_birth_place" : "Blunsdon St Lenards"
}
{
        "_id" : ObjectId("5906ab35e9379091b11c4fa7"),
        "birth_county" : "WIL",
        "birth_place" : "Blunsdon St Lenards",
        "verbatim_birth_county" : "WIL",
        "verbatim_birth_place" : "Blunsdon St Lenards"
}

**Comment by Captainkirkdawson** [comment] 2020-02-19 23:45
Just tested FC1 and ONLY the first word of the entry typed into the birth place field is matched. We can do better than that with the text index
In fact I wonder what it really does; If St Ann is entered for Nottinghamshire one gets primarily Sutton
West in Nottinghamshire gives 1 West and 1 Wistow yet a search for weston gives a number of entries for 
West Markham. Will not pursue FC1 any further it makes zero sense

**Comment by Captainkirkdawson** [comment] 2020-03-22 14:50
As part of the investigation into places with no location I wrote and ran an extract rake task to identify those places. There are now 513 up from 353 2 months ago. The list is at https://drive.google.com/drive/u/1/folders/1MQdWRjfwq7PUlWezwdoVzYPWbE5jvN5h

**Comment by Captainkirkdawson** [comment] 2020-03-22 14:52
The no locations report shows entries for Places that puzzle me. eg
St Philip & Jacob 4A 
St Philip & Jacob 4B 
St Philip & Jacob 4C 
St Philip & Jacob 4D 
St Philip & Jacob 4E 
St Philip & Jacob 4F 
St Philip & Jacob 4G 
St Philip & Jacob 4H 
St Philip & Jacob 4I 
St Philip & Jacob 4K 
St Philip & Jacob 4L 
St Philip and Jacob

**Comment by richardofsussex** [comment] 2020-03-22 15:36
Crathie & Braemar: see https://visionofbritain.org.uk/place/20197
Cleckeaton (WRY) will be a typo for Cleckheaton, I guess.

**Comment by richardofsussex** [comment] 2020-03-22 15:42
Rhynie & Essie: https://visionofbritain.org.uk/place/16495
Aboyne & Glantanner: https://visionofbritain.org.uk/place/16903
Keithhall & Kinkell: https://visionofbritain.org.uk/place/16903
Tarland & Migvie: https://visionofbritain.org.uk/place/17017

**Comment by FreecenBren** [comment] 2020-03-22 18:13
St Philip  <https://www.genuki.org.uk/big/eng/GLS/Bristol/StPhilipStJacob> & St Jacob, Bristol, Church of England
Gloucestershire Bristol St Philip & St Jacob St Philip & St Jacob, 
All in the PARMS for Gloucestershire.

HO107/1949
St Paul
St Paul In , St Philip & St Jacob
1851
 

HO107/375
Bristol City
St Philip & St Jacob, St Stephen , Temple or Holy Cross, St Thomas , St Werburgh
1841
 

RG9/1717
Bristol St Paul
St Philip & Jacob
1861
 
There are others.

**Comment by Captainkirkdawson** [comment] 2020-03-22 19:57
@FreecenBren  
The initial point I was making was there is **no such place** as St Philip & Jacob 4A or St Philip & Jacob 4B etc 
Nor is there a **Place** called St Philip & Jacob. There is a **building** called St Philip & Jacob. There may be parish called St Philip & Jacob in the census. But the Place is Bristol.

A Place has many Pieces. A Piece is for a specific parish of part thereof and the Piece can have many subplaces

**Comment by FreecenBren** [comment] 2020-03-22 21:09
It may not be a Parish now but according to the National Archives and the
Census Images it was a Civil Parish and people did live there and  It was
recorded as such.
This is from the National Archives page. From 1841.

https://discovery.nationalarchives.gov.uk/details/r/C3761111

As such that is why it is in the Census as it is a Civil Parish.

Hundred: Barton Regis. Parish: (6)(3)St Philip and St Jacob (part). Rest in
HO 107/375..
Reference: HO 107/378
Description:

Hundred: Barton Regis.

Parish: (6)(3)St Philip and St Jacob (part). Rest in HO 107/375.







This is one census page showing the Civil Parish in the top left hand
corner which is what was transcribed.
The Civil Parishes are all about the transcribing as we use them every day
doing the transcriptions. They are all on the appropriate  PARMS files as
well.
So wHy  are the Civil Parishes not searchable?
We have mentioned this before.
They are all searchable on FC1 by typing in the Civil Parish name should
you chose to.
Street
Piece Ecclesiastical District
Enumeration District Civil Parish
Surname Census Place





This issue we only had today  with a researcher query we were sent.
It was one of Geoff’s issues for Somerset that FC1 Found that FC2 could not.
It opens up other things for discussion.

My question would be is, why is the Civil Parish not searchable on FreeCEN
Two when we use it everyday when doing the transcribing and it also
 relates back to the PARMS that is viewable from the STATS pages for both
FC1 and FC2.

FC2 Stats / Transcription page GLS 1841
378 Barton Regis St Philip & St Jacob, Online
The problem is I have my Transcriber hat on  and so probable not seeing the
other side.
I will leave it all for your discussion as I need to spend time catching up
on other things for FreeCEN.

**Comment by Captainkirkdawson** [comment] 2020-03-22 23:41
We continue to talk at cross purposes unfortunately.

I accept fully that Gloucestershire has a Census Place called Barton Regis and that there are 2 Civil Parishes in that Place. Stapleton and St Philip & St Jacob. 
I am questioning and others like them Reference:	RG 10/2559
Description:	
Registration Sub-District 4D St Philip and St Jacob.
Civil Parish, Township or Place: St Philip and St Jacob(pt) (Divided between RG 10/2567-2568 and 2570)
where the **Place is recorded as St Philip and St Jacob 4D** etc. These are not Census Places. Clearly the Civil Parish is St Philip and St Jacob
I cannot comment of the questions you raise with respect to the search.

**Comment by PatReynolds** [comment] 2020-03-23 08:53
Hi Brenda, story #752 covers the civil parish search.  It needs allocating to either the group oif issues we hope to deal with sooner rather than later, or the group that will be done after we have dealt with the facilities for coordinators, proofreaders and transcribers - it should have been picked up and allocated, but wasn't so I've flagged it for discussion at the next scrum.

**Comment by PatReynolds** [comment] 2020-04-01 12:28
Brenda's (potential) issues:
"This issue we only had today with a researcher query we were sent.
It was one of Geoff’s issues for Somerset that FC1 Found that FC2 could not." @geoffj-FUG could you clarify on this - it may well be covered by the issues/stories relating to researcher facilities on FC1 but not FC2 to be implemented sooner rather than later, and those to be implemented later as they are less important (epic #743), or related to the complexity of place (epic #744)

"My question would be is, why is the Civil Parish not searchable on FreeCEN"
Now story/issue #752

FC2 Stats / Transcription page GLS 1841
378 Barton Regis St Philip & St Jacob, Online
 - I can't see the problem, so have asked Brenda to clarify 1/4/2020

**Comment by PatReynolds** [comment] 2020-04-29 17:42
Closing, as 'place' per se is not a FreeCEN concept.  The totality of stories involving geographic locations is the epic.

**Closed by PatReynolds** 2020-04-29 17:42 UTC
Labels: P27, Place, needs info, sprint backlog
