### ISSUE TITLE
Add search in Yorkshire for birth county was 201787647 Website Problem (ian stimson)

### ISSUE THREAD

**Issue by ghost** [FreeUKGen/FreeCENMigration#1229] opened 2021-05-24 21:18 UTC
One component of  #238 
Issue reported by **ian stimson** at 2021-05-24 12:07:27 UTC
Time: 2021-05-24T11:52:34+00:00
Session ID: 
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
When I look for Thomas  Driver (Exact) in 1891, census county born West Riding Yorkshire and census county also WRY, I can find him on Freecen 1 , but Freecen 2 gives no result. If I select all three Ridings no result . If I select  Yorkshire  no result . 
He was born and lived in Silsden (9,000 inhabitants) but Silsden is not on your list of places  in freecen 1 nor in freecen 2. 
    
E2 U4 S5 C6:P17

**Comment by Captainkirkdawson** [comment] 2021-05-24 21:20
This is an interesting issue which will require further research. Likely caused by the birth place being registered as Yorkshire.

In the meantime if you search for him simply in the census county you will find the records for him and his family. See the attached 2 images.

The census search is conducted by the District place name; in this case Silsden is a civil parish in the District of Skipton. That is why you will not see Silsden in the list of Census places and why in FR2 we explicitly call it a Census District both in the search and the results.

**Comment by Captainkirkdawson** [comment] 2021-05-24 21:30
https://www.freecen.org.uk/search_records/5c5ddf7af4040b0fa7003553/thomas-driver-1891-yorkshire-west-riding-skipton-1851-?locale=en
        "transcript_dates" : [
                "1851-*-*"
        ],
        "search_dates" : [
                "1851-*-*"
        ],
        "location_names" : [
                "Skipton"
        ],
        "search_soundex" : [
                {
                        "first_name" : "T520",
                        "last_name" : "D616",
                        "type" : "p"
                }
        ],
        "transcript_names" : [
                {
                        "first_name" : "Thomas",
                        "last_name" : "DRIVER",
                        "type" : "primary"
                }
        ],
        "chapman_code" : "WRY",
        "record_type" : "1891",
        "place_id" : ObjectId("590261d8e9379091b1b65899"),
        "birth_chapman_code" : "YKS",
        "freecen_individual_id" : ObjectId("5c5ddf49f4040b0fa700082a"),
        "search_date" : "1851-*-*",
        "digest" : "A99CMfC8AkpVM6ovbFrv5Q==",
        "u_at" : ISODate("2021-05-24T11:48:11.262Z"),
        "c_at" : ISODate("2019-02-08T19:58:50.070Z"),
        "search_names" : [
                {
                        "_id" : ObjectId("5c5ddf7af4040b0fa7003554"),
                        "first_name" : "thomas",
                        "last_name" : "driver",
                        "origin" : "transcript",
                        "type" : "p",
                        "role" : null,
                        "gender" : "m"
                }
        ],
        "birth_place" : "Silsden",
        "embargoed" : false

**Comment by Captainkirkdawson** [comment] 2021-11-02 15:22
Need to add Yorkshire as a county searched for births

**Comment by PatReynolds** [comment] 2022-08-24 08:12
Entry is https://www.freecen.org.uk/search_records/5c5ddf70f4040b0fa7002277/thomas-driver-1891-yorkshire-west-riding-skipton-1822-?locale=en
I viewed the original on a subscription site.  The enumerator has written the place of birth for the first entry on the page (our Thomas Driver is about 1/3 of the way down) "Yorkshire - Silsden".  And for the second "Yorkshire - Leeds".  This is where the page gets interesting as there are no more words: for each entry there is a dash under Yorkshire, two dashes (Yorkshire and Leeds), one long dash (from Y to s) or nothing at all.  
TWYS suggests county should be 'Yorkshire' and place should be 'Leeds'.

**Comment by PatReynolds** [comment] 2022-08-24 08:40
As the County of birth is transcribed as "Yorkshire, West Riding (or Yorkshire)" this record is not finable by searching "Yorkshire" or "West Riding of Yorkshire".

The search engine is fine: it is the the transcription where the issue lies.  Piece is: 1891	Yorkshire, West Riding (WRY)	Skipton	Silsden	St James	3501

**Comment by PatReynolds** [comment] 2022-09-07 08:50
Pat to check - this may be a chapman code error (that's what the search of county of birth is on).

**Comment by DeniseColbert** [comment] 2022-09-07 08:53
This relates to the hierarchy table in Appendix B in Coords/Validators handbook. YKS/Ridings/ CHI/Islands etc. E.g. born in IOW, could be enumerated as HAM

**Comment by PatReynoldsFUG** [comment] 2024-04-10 10:38
Update 10 Apr 2024: The birth county in FreeCEN is now "Yorkshire, West Riding (or Yorkshire)" and the place of birth is "Silsden (or Leeds)".  These two need to agree in heirarchy so as not to confuse the user, I.e. either
Yorkshire : Silsden first or Yorkshire, West Riding : Leeds first. 
However, a search for Thomas gets no results (date of birth range 1820-30, county of birth, neither "Yorkshire" nor "West Yorkshire".  I tried changing the name to John Smith, and this produced results.
<img width="911" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVZMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e24aa0dc388d8c7ece88e2e3c268e459c1be888c/image.png" alt="John Smith image.png" />

**Comment by Vino-S** [comment] 2024-04-17 09:22
@geoffj-FUG will look into this

**Comment by DeniseColbert** [comment] 2024-05-01 09:42
Done, closing

**Closed as completed by DeniseColbert** 2024-05-01 09:42 UTC
Labels: bug, P17
