### ISSUE TITLE
Merchant Vessel Page Numbers

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1103] opened 2021-01-10 09:58 UTC
The Instructions state:
For Merchant Vessels, there may be no Page Numbers: Use "0" (zero)
However Page number 0 creates an error.
Records in FC1 contain the page number 0 so we need to modify the page number test to accept it.
Geoff

E0 U6 S 9 C6: P21

**Comment by Captainkirkdawson** [comment] 2021-01-22 20:54
@geoffj-FUG was this for an original upload of a traditional file or simply an error in my download of a vld file. Solutions are quite different

**Comment by geoffj-FUG** [comment] 2021-01-22 21:50
Kirk

 

It looks like our page number test parameters that needs amending.

 

At the moment page 0 is not a valid page number (I think?). We need to make it valid.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2021-01-22 22:44
@geoffj-FUG can you provide an example of the failure please.

A 0 is a valid digit and a non digit is the only cause of an error message on a page number. 

A warning will be issued if it is less than the previous page number. 

So without a case I cannot investigate and see why an error message would be generated

**Comment by geoffj-FUG** [comment] 2021-02-09 07:38
Kirk

 

The problem piece disappeared with the test3 reset. I will try to find another one.

 

Geoff

**Comment by geoffj-FUG** [comment] 2021-02-09 07:39
Kirk
Have a look at RG10_5549 in test3.
We have errors for page number 1 and page number 2.
May be related.
Geoff

**Comment by Captainkirkdawson** [comment] 2021-03-10 05:07
@geoffj-FUG cannot find RG10_5549 in test3.

**Comment by geoffj-FUG** [comment] 2021-03-10 10:27
Kirk
I have re-loaded the piece.
Geoff

**Comment by Captainkirkdawson** [comment] 2021-03-10 23:34
@geoffj-FUG sorry but I do not see it on test3

**Comment by Captainkirkdawson** [comment] 2021-03-10 23:49
@geoffj-FUG File RG10_5549 in test3 has no page number errors. Are we looking at the correct file??

**Comment by Captainkirkdawson** [comment] 2021-03-11 00:17
@geoffj-FUG 
Reason I could not find the file was I was looking in Somerset and it was in Cambridgeshire.
These page number issues have nothing to do with Merchant Vessels.
Regardless the fix I deployed for **Page number reported as error with ED in middle of page#1137** would apply to this situation.
I reprocessed the file and it has fixed the issue.

However as I said this is not a Merchant Vessel issue and I need an example of a failure for that to investigate.

**Comment by geoffj-FUG** [comment] 2021-03-11 06:21
Kirk

 

I have uploaded file RG12_1918 to test3. This file had a series of vessels against ED 0#8 from row 7372 onwards.

 

The page number problem appears to have cleared with yesterday’s fix.

 

Geoff

**Comment by geoffj-FUG** [comment] 2021-03-11 09:50
Kirk

 

It’s the top file in CSVBatches for somt.cen. County SOM.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2021-03-11 18:21
@geoffj-FUG 
The problem with using RG12_1918 is that it was created by my vld download and then uploaded **Hence issues may be caused by either component**. It is therefore not a file that is especially useful for diagnosing an upload issue. But perhaps I can modify it as a test piece

**Comment by Captainkirkdawson** [comment] 2021-03-11 18:48
@geoffj-FUG 

I can now confirm the following.

That the VLD Download does NOT process the 0#8 ED entries correctly. This will be addressed in as a story under the VLD tools epic
Manage vld data files with online tools in CEN2#854

That a Merchant Vessel Page Number of 0 is correctly processed. 
That a Merchant Vessel Page Number of blank creates an Error message.

This is what I believe the specification calls for.

However it would be possible to permit a blank page number for the 0#8 ED. Please indicate if this is a requirement. If it is not we will close this story

**Comment by geoffj-FUG** [comment] 2021-03-12 05:01
Kirk

 

If the ED number is entered on that row as 0#8 then there must be a page number.

If the ED is blank it is OK, but not compulsory, for the page number to be blank.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2021-03-12 16:19
@geoffj-FUG sorry to be so dumb but we are miscommunicating.
I was talking about subsequent vessels where a folio number has been entered and what to do with the page validation at that point.
Currently if there is a new folio number there must be a page number. It can be 0.

 I was asking if I should permit a blank page number if there is a folio number for a vessel on non ED lines

**Comment by geoffj-FUG** [comment] 2021-03-12 21:37
Kirk

 

If there is a folio number there should be a page number.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2021-03-12 22:27
TY @geoffj-FUG  will leave code as is and close

**Closed as completed by Captainkirkdawson** 2021-03-12 22:27 UTC
Labels: P21
