### ISSUE TITLE
136379381 Website Problem (Anthony Bennett)

### ISSUE THREAD

**Issue by FreeUKGenIssues** [FreeUKGen/FreeCENMigration#678] opened 2019-04-28 15:24 UTC
Issue reported by **Anthony Bennett** at 2019-04-28 11:09:41 UTC
Time: 2019-04-28T11:08:47+00:00
Session ID: 02bbcfb4c5c09b32b75a8fdcfc6248a5
Problem Page URL: []()
Previous Page URL: [https://www.freecen.org.uk/contacts/new](https://www.freecen.org.uk/contacts/new)
Reported Issue:
I am repeatedly receiving the message "We encountered a problem completing your request" when attempting a search.  The same thing keeps occurring when I retry.    

![Screenshot](https://freecen2.freecen.org.uk/uploads/contact/screenshot/5cc589f5f493fd418ea4ef06/_old_)

**Comment by Captainkirkdawson** [comment] 2019-04-28 15:29
This will be a difficult issue to diagnose due to bot accesses creating a large number of similar events. brazza logs show 313 such crashes alone today up until 15:00. Since these are trapped events they are not reported ito errbit

**Comment by Captainkirkdawson** [comment] 2019-04-28 16:37
brazza had 309 crashes of /home/apache/hosts/freecen2/production/app/controllers/search_records_controller.rb:63:in
and 5 of 	/home/apache/hosts/freecen2/production/app/controllers/places_controller.rb:99:in `for_search_form'

**Comment by Captainkirkdawson** [comment] 2019-04-28 18:00
I believe that the type A and type B crashes are from bots. THE TYPE C errors are user level experiences and are a serious performance issue and may be the cause of many of the comments made about FreeCEN2.
Have confirmed that his first search crash was for an Emily Rule rather than what he reported. It is interesting that the search queries associated with TYPE C are present in the database. Looks very much like a timing issue. That we are attempting to read the record before it has been written.

**Comment by Captainkirkdawson** [comment] 2019-04-28 19:30
There are a couple of ways of handling this. Firstly by waiting for a write completion or secondly through code changes. I am reluctant to adopt the latter until we have deployed the multi modal code as these areas of code are different there. Consequently I will experiment with a write timeout in mongoid.yml

**Comment by Captainkirkdawson** [comment] 2019-04-28 21:19
Applied a write majority to saki

**Comment by Captainkirkdawson** [comment] 2019-04-29 14:31
saki logs show only 2 type C occurrences today. Both messages are correct there were no such queries. 
Propose to deploy same fix to other servers.

**Comment by Captainkirkdawson** [comment] 2019-04-30 14:38
Logs show only 3 type C occurrences over all 5 servers today. Those were correct.
As this was a configuration change it is implemented and deployed

**Comment by richpomfret** [comment] 2019-05-15 14:36
Closing - no further incidences spotted.

**Closed** 2019-05-15 14:36 UTC
