### ISSUE TITLE
File processing email was sent to wrong Coordinator

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1403] opened 2022-04-04 14:18 UTC
![image.png](https://images.zenhubusercontent.com/5cab6cc818447254e461e741/946c81a9-dd59-489b-883f-902ea6e50693)

This file is definitely a NTH file, but the email has the wrong COORD in the 'To' field, the actual NTH COORD is in the cc field.

Chris Prior is COORD for DBY and DEV
Ali Hill is COORD for NTH

They are listed correctly on https://www.freecen.org.uk/syndicates so why is the email going to the wrong COORD?

**Comment by PatReynolds** [comment] 2022-04-06 15:57
@DeniseColbert to investigate

**Comment by PatReynolds** [comment] 2022-05-04 15:54
Believe caused by a transcriber being allocated to the wrong syndicate.  It is believed that this issue is now resolved, so closing.

**Closed as completed by PatReynolds** 2022-05-04 15:54 UTC
