### ISSUE TITLE
Integrate all components to use places in our Gazetteer.

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1305] opened 2021-10-16 20:27 UTC
We have expended considerable effort in developing our own Gazetteer which is a high quality set of place names and their location. (georeferenced). It has almost 50,000 entries.
CSVProc uses this for establishing locations.
VLD entries currently use a small low quality place collection that in many cases are not georeferenced.
It is proposed to convert Vld and all searches to use the Gazetteer. This will enable us to reactivate the Nearby search feature.
This is an umbrella story

**Comment by Captainkirkdawson** [comment] 2021-10-16 22:22
@geoffj-FUG @PatReynolds @DeniseColbert @rhodamackenzie @FreecenBren 
test3 has been updated with a large number of detailed stories that implement this overall concept. Rather than try to focus on the individual stories many of which are difficult to test I believe acceptance should be based on testing the overall effect of their implementation. The search page has a number of changes which are covered  this post.
![searchpage.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/49a8f468-ec08-4797-bc1b-304fe71b8aea)
The results displays of a 'normal' search are unchanged.

**Comment by Captainkirkdawson** [comment] 2021-10-16 23:00
Looking at the Nearby search feature
![searchresult1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/ca461b90-221a-4a4e-ad2b-1da5a76e7dd7)
The places in the search are shown in the About this Query
![About.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/ce5e784a-297e-4509-9452-3f83b577a1eb)
What is clear is that some place in the gazetteer still have incorrect places; BUT remember this is the TEST environment and no corrections have been made to it. However the majority are correct

**Comment by Captainkirkdawson** [comment] 2021-10-16 23:16
@geoffj-FUG @rhodamackenzie @PatReynolds @DeniseColbert @FreecenBren 
There have also been some additions to the displays for Coordinators
![places1.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/9fc056f7-27db-4725-9801-379a1ce0e664)
![places2.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/1de6e4b7-b68a-46b2-838d-25b98d1e1712)
![places3.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/042b1baf-7690-4bf5-9cc8-e52313696296)
![places4.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/89750837-fedf-4a33-a856-cde6e0bf5f91)
![places5.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/1023bd59-7e6c-4ca2-9cdf-dd8c5d22e12c)

**Comment by Captainkirkdawson** [comment] 2021-10-16 23:20
The VLD upload and CSVProc are both modified to interface with this Integrated system.
Testing should be focused on the preceding capabilities as well as confirmation the uploads work as expected.. The detailed stories should be closed and new stories written to address problems found with its implementation.

**Comment by rhodamackenzie** [comment] 2021-10-17 11:00
Thank you Kirk, this is very impressive and represents a lot of mental and physical work.

**Comment by geoffj-FUG** [comment] 2021-10-17 11:31
Kirk, Pat

 

Isn’t it strange how Kirk and I are both quietly working on the same thing but different problems?

 

I have attached an item that I have written for the next FreeCEN newsletter. I am trying to address the rubbish that some validators are putting into the Gazetteer.

The items that Kirk has highlighted as ‘not near to his search centre’ are symptoms of this. However he is working in test and spurious info gets in there. I would be interested in what comes up as this goes live.

 

I am hoping that by explaining some of the functionality of the Gazetteer people might realise that it is not just another personal place database that anything can be put in but an important tool that helps drive FreeCEN.

 

My suggestions on OVB and OVF are an effort to take a more accurate approach to that part of our data.

 

Now my concern - At present a ‘soft’ approach has been taken on vld files and a back door has been left open to allow vld files to be uploaded. In these cases no additional validation is done because the files are regarded as validated – irrespective of how well or how inaccurately they have been validated. This is perpetuating the results that vldrev has allowed to happen. This was due to each validator having their own database which was not quality controlled. (I am sure that some of my own validations would throw up queries if we tested them against the Gazetteer simply because our way of thinking has changed). The longer we allow newly validated vlds to be uploaded the less accurate our searches will be

 

Given these new search developments do we need a quality control of vlds on upload to ensure that entries are linked to the Gazetteer correctly? We have that control through CSVProc but do not through valdrev.

 

Geoff

**Comment by Captainkirkdawson** [comment] 2021-10-17 15:05
@geoffj-FUG I like your article on the Gazetteer

**Comment by PatReynolds** [comment] 2021-10-18 09:35
Excellent - thank you Geoff!  

Is it premature to mention Nearby Places searching depends on the Gazatteer - and this feature uses lat and long rather than county (so very useful to our users)?

**Comment by PatReynolds** [comment] 2021-10-18 10:54
Thanks, Kirk!  I think there may be some erroneous geolocations in the gazattteer that have been revealed by this wor.

![image](https://user-images.githubusercontent.com/6338822/137714901-65ddf813-8370-4513-99b2-5b9f9eee6587.png)
result included 10 people from Lancashire censuses (born Lancashire).  North and South Bury seem to be incorrectly geolocated (Google maps suggests that they are 154miles from Hardingstone - these distances are longer than straight line).  

One from King's Lynn North (Google suggests 78 miles). North Damerham (Wiltshire) (37.7 miles) was also searched (Google says 123 miles).

The other places searched suggests the issue is not with Hardingstone.

**Comment by Captainkirkdawson** [comment] 2021-10-18 14:26
Yes that is correct @PatReynolds but that is not an error in the software but an incorrect entry in the Gazetteer that is revealed by the software.

**Comment by Captainkirkdawson** [comment] 2021-10-18 23:23
Wording on too many results changed to include suggestions.
![toomany.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/729401a8-b67b-4903-8601-0b6d2c1699b7)

**Comment by geoffj-FUG** [comment] 2021-10-19 00:12
Pat

 

I do not believe that it is too soon. The system is becoming very different
to FC1. It is important that people can recognise the changes.

 

If people start to realise the implications of abusing the system they may
temper their habits.

 

Geoff

**Comment by PatReynolds** [comment] 2021-10-19 08:28
Thanks, Geoff - please add it - let me know if you want me to write something.  Best wishes, Pat

**Comment by PatReynolds** [comment] 2021-10-19 08:50
Loving the "reduce" feature, @Captainkirkdawson!

**Comment by PatReynolds** [comment] 2021-10-21 14:44
Testing: when I search in a place (e.g. Parratt in Huddersfield, WRY), and then use 'revise serch' button to go back and add 'nearby places', while WRY is still selected, Huddersfield is lost.  Other selections e.g. birth county, census year, gender, work as expected.  

I have checked on live, and there the 'revise search' button works as expected.

No other issues arose.

**Comment by Captainkirkdawson** [comment] 2021-10-21 15:26
@PatReynolds good catch

**Comment by Captainkirkdawson** [comment] 2021-10-22 21:56
@PatReynolds solution identified for failure to retain the place name selected on a revise.

**Comment by Captainkirkdawson** [comment] 2021-10-22 23:09
Commenced the slow roll out of Integrate all components to use places in our Gazetteer.#1305 to CEN production.
5:07
Updated the configuration on all production servers so that app will continue to run as before

**Comment by Captainkirkdawson** [comment] 2021-10-22 23:14
Merged branch into master; no conflicts.

Deployed master to test3 running prior place linkages

**Comment by Captainkirkdawson** [comment] 2021-10-26 19:34
Test3 now running the new set up.

**Comment by Captainkirkdawson** [comment] 2021-10-26 19:35
Software deployed to production but running against the old database structure.
Commenced building the new database in the background.

**Comment by Captainkirkdawson** [comment] 2021-10-29 15:49
After refining the creation process to avoid processing chunks that were too big it is estimated that a further 6.25 days of processing will be required. All being well it should complete on Thursday November 4.

**Comment by Captainkirkdawson** [comment] 2021-11-08 21:32
Processing completed; took 10 days in total.
Rebuilding Freecen2 Place Cache

**Comment by Captainkirkdawson** [comment] 2021-11-16 00:24
Completed and deployed

**Comment by PatReynolds** [comment] 2021-11-17 16:34
Thank you, @Captainkirkdawson ! So closing.

**Closed as completed by PatReynolds** 2021-11-17 16:34 UTC
