### ISSUE TITLE
Decide how to handle the 1841 Hundreds as far as place name and location are concerned

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#975] opened 2020-09-17 16:25 UTC
The 1841 census uses the Hundred as the Registration District and there is no Sub District name. 
All other later census documents use a Place name for both the Registration District and the Sub Districts that can be located in a Gazetteer and provided with physical coordinates.
Freecen2 and Freecen1 use District and Sub District place names for searches. 
The Freecen2 Place name collection does not include hundreds as they are areas and not specific places. Nor do gazetteers.
The Freecen1 Place name collection includes Hundreds (modified in format eg removal of -) and in  many (most?) cases a location
Freecen2 insists that a Sub District (Piece) has an entry in the Freecen2 Place collection before it will create search records for csv entries.
Researchers are generally ill informed about Hundreds and their names are not in common place usage.
How should we proceed?
Do we simply add (and complete if required) the hundred s and their locations from the Freecen1 place collection?
Do we add an Alternate Place Name that is the "main" community in the Hundred
Do we enter the 'Main" name as the place name wi the hundred as alternate

**Comment by PatReynolds** [comment] 2020-09-18 08:15
One potential is to use the cordinates given on wikipedia: eg https://en.wikipedia.org/wiki/Howdenshire

Or something more reliable eg https://www.geog.cam.ac.uk/research/projects/occupations/hundredmapping/

The existance of the hundred/wapentake is only going to be revealed in the detailed results (?is that correct?)

**Comment by Captainkirkdawson** [comment] 2020-09-18 14:38
Neither of those provide geographic coordinates as far as I can see.
But what about the question of how they should be entered. Howden (with alternate Howdenshire) or Howdenshire( alternate Howden ). Howden is already in Freecen2 Places collection because it was either a Registration District or Sub District in the later census
If you look at the actual census document you will see that the Registration District or Sub District were actually Howden in 1841 it is just that TNA decided to index their documents by hundred in 1841.
![howden](https://user-images.githubusercontent.com/2874694/93610463-52e89a00-f98a-11ea-8da5-7a3dbe145686.png)

So in my mind we should use Howden (alternate Howdenshire) Then all census years will fall into line

**Comment by PatReynolds** [comment] 2020-09-21 15:34
We would have to ask for the University of Cambridge data.  The wikipedia data is available at the top right of the page: ![image.png](https://images.zenhubusercontent.com/5b695a5dac3a200155c765e3/204a0c16-f006-4b93-b362-9a503050f866)

**Comment by PatReynolds** [comment] 2020-09-28 16:36
The issue is the hundrends/wapentakes have no lat and long - Pat to contact the Cambridge guys to see if we can have their georeferences.

**Comment by PatReynolds** [comment] 2020-10-04 17:01
Email sent to Cambridge 4/10/2020

**Comment by PatReynolds** [comment] 2020-10-26 10:09
Suggestion: where possible, while waiting for Cambridge to reply, take from wikidata - e.g. https://www.wikidata.org/wiki/Q7877741, if not possible, use  the placemame location (in this case Uggescombe Hundred).

**Comment by Captainkirkdawson** [comment] 2020-10-26 14:13
Unfortunately it is not a universal source ie not all hundreds are included.

**Comment by PatReynolds** [comment] 2020-10-26 17:06
County coordinators to use the wikidata where possible, and use the place name if not there.  First step is just to do those hundreds/wapentakers where they have transcriptions.

Pat will liaise with Geoff on this.

**Comment by PatReynolds** [comment] 2020-10-27 12:19
I emailed @geoffj-FUG with decision 27/10/2020, and created issue #1037 for implementation, so closing.

**Closed as completed by PatReynolds** 2020-10-27 12:19 UTC
Labels: Policy
