### ISSUE TITLE
Part pieces for FreeCEN2 are not shown as uploaded for previously loaded VLDs

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1354] opened 2022-01-20 23:36 UTC
The issue is caused by there being a greater granularity in the pieces for 1841/1851 with freecen2 than for freecen1. This arose from separating the pieces into components based on the hundreds and adding  A, B, C etc to the number.   If you look at the number completed in the reports it is close to what you think is completed. For 1851 and onwards  the number of pieces is close to what you would expect based on freecen1 except freecen2 has a few more based on putting them in the correct county again they have an additional letter A etc.
Take the example of Dorset.
![Dorset.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/42d27ef4-c49d-4a1a-bb19-24947de72af2)
Looking at the site statistics
![dorset2.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/c2851afb-cbf0-4d71-95eb-b7b83f314e2e)
This shows that the Records is reporting the correct number of files.
The coordinator MikeS has provided a report from his records.
![mikeS .png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/e59c8b00-62c8-4152-8129-d1464ad51953)
This again confirms that the correct number of uploaded files even for 1871 when CSV uploads are involved.
The number of available pieces that we are reporting is high because of a) greater granularity and b) some pieces being reported into the "correct" county on FreeCEN2.

**Comment by Captainkirkdawson** [comment] 2022-01-21 00:26
We were faced with a similar issue with the ability to upload CSVProc files and added the ability to confirm when the last part of a piece had been added. 1) We could do something similar in this situation for uploading new VLD files.
2) we could add an edit option to enter an Online and date of online to a piece. This could be used for pieces  cutover into other counties 3) we could run a rake task for existing VLD and add an Online and date of online for all pieces with added alphabetic characters to their name using the numeric part as the selector of the piece. This would avoid having to manully edit several thousand pieces.

**Comment by Captainkirkdawson** [comment] 2022-01-21 00:27
@geoffj-FUG your views on these options would be appreciated

**Comment by geoffj-FUG** [comment] 2022-01-21 04:48
Kirk
I see a conundrum.
Lets take 1851 as an example. Somerset completed this year some time ago and all the files are uploaded as vld files. But the new PARMS will have broken some of the pieces up as they are all large. The stats will show some missing files but they are all online.
I have previously actioned a researcher contact action report for HO107_1846 (I think). As a result I deleted HO107_1846 and broke up the spreadsheet into the new pieces. They were than uploaded as csv files. So our stats show 1 vld removed and 2 csv added.
This problem is caused by the continuation of the loading of vld files beyond their use by date. If this was not happening we could simply regard vld files as complete and record csv files in their separate parts. Simple! But we have generated the problem for ourselves by continuing with both systems.
The problems are avoidable. It is another example like the flack that was going around with my name attached to it over the London breakup. I chose to ignore it and let it die. The Coordinators who were generating the problems and complaints were the ones who did not cooperate during cutover and were complaining on the message boards that I got it wrong. The breakup was correct. They just chose to ignore it and we ended up with pieces transcribed twice.
You will have seen my email on the boards to validators yesterday. Which counties have the most issues? See previous paragraph.
Until we close off vld entries and use the software properly as it was designed we will continue to generate problems such as this one counting file completions.
Can we identify which vld files came from FC1? If so all of these can be marked off as complete. Any files being uploaded now will need to be split into the parts of the PARMS and the process adopted that we use for csv files. We will need to upload vld files in parts so that we can track them. That is the simplest and most manageable option that I can see.
Geoff

**Comment by Captainkirkdawson** [comment] 2022-01-21 16:42
@geoffj-FUG  your response seems to indicate support for options 1 and 3 which address VLDs loaded for pieces of the same county. Is this the case? Your comments do not address how to deal with VLDs for Complete and partial cutover pieces where 'ownership and transcription' is in a different county coordinator.

**Comment by geoffj-FUG** [comment] 2022-01-22 01:23
I am sorry. I am frustrated at the problems that vld files and their continuation are causing. This is just one example. 
(I am trying to work through the Gazetteer and the Counties that are causing the most headaches seem to be biased towards the Counties who are still using vlds. Hence my frustration). It would all be far simpler if we only used the upgraded system.

My view is that the Coordinator of the original County is the one responsible for completing the records. For vld pieces uploaded post cutover option 1 is the answer.
However if we can identify those pieces uploaded to FC1 and transferred then option 3 would bring us up to date - because FC1 would not take part of a piece.

Geoff

**Comment by Captainkirkdawson** [comment] 2022-02-03 18:04
Rake task written that deals with the need to link the new part pieces of freecen2 with previously loaded vld files. It has been run in production and produces much better results. The code also deals with part pieces for another county so no action is required of coordinators. See new version for Dorset
![dorseta.png](https://images.zenhubusercontent.com/5b68ae684b5806bc2bdefcf0/5850201f-9b20-4ffd-a3be-1e475b475e83)
There remain a few issues to be resolved at the detail level.

**Closed as completed** 2022-02-06 23:09 UTC
